### ISSUE TITLE
Version 1.6 crashes.

### ISSUE THREAD

**Issue by TommieIV** [Wurst-Imperium/Wurst-Client#100]
I updated to version 1.6 after cleaning out all Wurst files and I got this crash.

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Oh - I know what I did wrong!

Time: 2/27/15 10:12 AM
Description: Initializing game

java.lang.NoClassDefFoundError: java/util/Base64
	at tk.wurst_client.alts.Encryption.encrypt(Encryption.java:55)
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:357)
	at tk.wurst_client.files.FileManager.init(FileManager.java:89)
	at tk.wurst_client.Client.startClient(Client.java:54)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:616)
	at net.minecraft.client.Minecraft.run(Minecraft.java:429)
	at net.minecraft.client.main.Main.main(Main.java:127)
Caused by: java.lang.ClassNotFoundException: java.util.Base64
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.alts.Encryption.encrypt(Encryption.java:55)
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:357)
	at tk.wurst_client.files.FileManager.init(FileManager.java:89)
	at tk.wurst_client.Client.startClient(Client.java:54)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:616)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:429)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.6 (latest: unknown)
	Operating System: Linux (i386) version 3.16.0-30-generic
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 144721288 bytes (138 MB) / 266661888 bytes (254 MB) up to 1349779456 bytes (1287 MB)
	JVM Flags: 5 total; -Xmx1300M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Mesa DRI Intel(R) 945GM x86/MMX/SSE2 GL version 1.4 Mesa 10.3.2, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
Try updating your Java.
