### ISSUE TITLE
CmdManager CrashCmd NotApplicable?

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#1125]
I was debugging wurst in eclipse (Got it to work)
Then I added crash cmd and it gave me this:

```
[20:06:09] [Client thread/INFO]: Setting user: Player261
[20:06:09] [Client thread/INFO]: (Session ID is token:lol:Player261)
[20:06:11] [Client thread/INFO]: LWJGL Version: 2.9.1
[20:06:11] [Client thread/INFO]: Reloading ResourceManager: Default
If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[20:06:12] [Client thread/ERROR]: Couldn't initialize twitch stream
[20:06:12] [Sound Library Loader/INFO]: Starting up SoundSystem...
[20:06:12] [Thread-6/INFO]: Initializing LWJGL OpenAL
[20:06:12] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:06:13] [Thread-6/INFO]: OpenAL initialized.
[20:06:13] [Sound Library Loader/INFO]: Sound engine started
[20:06:19] [Client thread/INFO]: Created: 512x512 textures-atlas

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Who set us up the TNT?

Time: 6/30/15 8:06 PM
Description: Initializing game

java.lang.Error: Unresolved compilation problem: 
	The method addCommand(Cmd) in the type CmdManager is not applicable for the arguments (CrashCmd)

	at tk.wurst_client.commands.CmdManager.<init>(CmdManager.java:39)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:52)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:561)
	at net.minecraft.client.Minecraft.run(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.commands.CmdManager.<init>(CmdManager.java:39)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:52)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:561)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: ~~ERROR~~ NullPointerException: null
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 95139568 bytes (90 MB) / 370147328 bytes (353 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.2.46, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
#@!@# Game crashed! Crash report saved to: #@!@# /Users/FireFolder/git/Wurst-Client/Wurst Client/./crash-reports/crash-2015-06-30_20.06.20-client.txt
[20:06:20] [Client Shutdown Thread/INFO]: Stopping server
AL lib: (EE) alc_cleanup: 1 device not closed
 ```
Then I went and downloaded a fresh version of the Wurst source code and took the src folder and replaced it with the one in my workspace (I checked) yet when launching I still get this error
P.S I am not on Windows and i was able to get it to launch before

**Comment by scriptinator** [comment]
Nevermind close and reopen project then do Project -> clean
