### ISSUE TITLE
CRash error report : SSm mineplex

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1147]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Don't do that.

Time: 04.07.2015 17:20
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1327)
	at net.minecraft.client.Minecraft.run(Minecraft.java:412)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Notch_s_hero'/70409714, l='MpServer', x=74,67, y=17,17, z=56,88]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 40,00,20,00,42,00 - World: (40,20,42), Chunk: (at 8,1,10 in 2,2; contains blocks 32,0,32 to 47,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 883552 game time, 13288956001 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntityOtherPlayerMP['fuchsi2012'/87091, l='MpServer', x=31,50, y=19,00, z=17,50], EntityOtherPlayerMP['fuchsi2012'/87091, l='MpServer', x=56,50, y=19,00, z=10,50], EntityItem['item.tile.leaves.jungle'/139278, l='MpServer', x=76,44, y=22,00, z=30,31], EntityItem['item.tile.grass'/138380, l='MpServer', x=45,31, y=16,00, z=33,31], EntityArmorStand['§eatasell'/140813, l='MpServer', x=28,40, y=23,86, z=34,48], EntityItem['item.tile.grass'/140561, l='MpServer', x=76,97, y=16,00, z=56,88], EntityPlayerSP['Notch_s_hero'/70409714, l='MpServer', x=74,67, y=17,17, z=56,88], EntityOtherPlayerMP['atasell'/134720, l='MpServer', x=108,50, y=16,00, z=82,50], EntityItem['item.tile.grass'/139417, l='MpServer', x=73,09, y=16,00, z=32,97], EntityItem['item.tile.leaves.jungle'/136220, l='MpServer', x=95,06, y=30,00, z=43,28], EntityOtherPlayerMP['atasell'/134720, l='MpServer', x=37,50, y=20,00, z=79,50], EntityOtherPlayerMP['Sturmritter'/99023, l='MpServer', x=40,50, y=20,00, z=83,50], EntityOtherPlayerMP['jscushman18'/134704, l='MpServer', x=31,50, y=19,00, z=17,50], EntityItem['item.tile.grass'/139432, l='MpServer', x=72,00, y=15,00, z=33,19], EntityItem['item.tile.leaves.jungle'/141103, l='MpServer', x=92,88, y=23,00, z=36,00], EntityItem['item.tile.leaves.jungle'/139315, l='MpServer', x=74,88, y=16,00, z=31,44], EntityItem['item.item.bone'/142390, l='MpServer', x=47,00, y=7,98, z=43,89], EntityItem['item.tile.leaves.jungle'/142267, l='MpServer', x=91,72, y=14,00, z=45,22], EntityItem['item.item.bone'/142395, l='MpServer', x=49,65, y=6,00, z=48,24], EntityItem['item.item.bone'/142398, l='MpServer', x=48,05, y=5,54, z=45,12], EntityCreeper['§eatasell'/134720, l='MpServer', x=28,40, y=22,51, z=34,48], EntityOtherPlayerMP['jscushman18'/134704, l='MpServer', x=69,50, y=33,11, z=46,50], EntityOtherPlayerMP['jscushman18'/134704, l='MpServer', x=40,50, y=20,00, z=83,50], EntityArmorStand['§efuchsi2012'/141126, l='MpServer', x=38,19, y=17,37, z=42,19], EntityItem['item.tile.grass'/141383, l='MpServer', x=76,88, y=16,00, z=31,41], EntityItem['item.tile.tallgrass.shrub'/142288, l='MpServer', x=61,47, y=15,50, z=55,31], EntityArmorStand['§eSturmritter'/141524, l='MpServer', x=40,11, y=22,62, z=42,94], EntityOtherPlayerMP['Sturmritter'/99023, l='MpServer', x=106,50, y=16,00, z=83,50], EntityArrow['arrow'/142318, l='MpServer', x=-9,31, y=4,00, z=68,84], EntityOtherPlayerMP['jscushman18'/134704, l='MpServer', x=36,50, y=17,00, z=50,50], EntityItem['item.tile.leaves.jungle'/139384, l='MpServer', x=76,94, y=24,00, z=28,50], EntityOtherPlayerMP['fuchsi2012'/87091, l='MpServer', x=104,50, y=35,00, z=51,50], EntityItem['item.tile.grass'/140156, l='MpServer', x=59,03, y=15,50, z=31,66]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"fa828eb":1059) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2954)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.15 (latest: 1.15)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 732540920 bytes (698 MB) / 1069023232 bytes (1019 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7400M Series GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by GummiBoat** [comment]
# *Duplicate: #642*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
