### ISSUE TITLE
I am trying to join a server and crash

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#1178]
```
Time: 7/10/15 10:10 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
	at net.minecraft.entity.DataWatcher.getWatchableObjectByte(DataWatcher.java:90)
	at net.minecraft.entity.EntityAgeable.getGrowingAge(EntityAgeable.java:89)
	at net.minecraft.entity.EntityAgeable.isChild(EntityAgeable.java:218)
	at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:187)
	at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(EntityAnimal.java:45)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:1835)
	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:278)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1887)
	at net.minecraft.world.World.updateEntity(World.java:1856)
	at net.minecraft.world.World.updateEntities(World.java:1705)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2367)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1268)
	at net.minecraft.client.Minecraft.run(Minecraft.java:379)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.getWatchableObjectByte(DataWatcher.java:90)
	at net.minecraft.entity.EntityAgeable.getGrowingAge(EntityAgeable.java:89)
	at net.minecraft.entity.EntityAgeable.isChild(EntityAgeable.java:218)
	at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:187)
	at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(EntityAnimal.java:45)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:1835)
	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:278)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1887)
	at net.minecraft.world.World.updateEntity(World.java:1856)

-- Entity being ticked --
Details:
	Entity Type: Ozelot (net.minecraft.entity.passive.EntityOcelot)
	Entity ID: 35808613
	Entity Name: §b§f§k:::§6Mi§9ku§f§k:::§r
	Entity's Exact location: 245.94, 65.00, 598.00
	Entity's Block location: 245.00,65.00,598.00 - World: (245,65,598), Chunk: (at 5,4,6 in 15,37; contains blocks 240,0,592 to 255,255,607), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1705)

-- Affected level --
Details:
	Level name: MpServer
	All players: 9 total; [EntityPlayerSP['sidjaja'/35808272, l='MpServer', x=213.60, y=65.00, z=589.17], EntityOtherPlayerMP['Smichelle_01'/33903081, l='MpServer', x=233.16, y=65.00, z=596.25], EntityOtherPlayerMP['dodolgaratu'/35694995, l='MpServer', x=222.27, y=69.76, z=601.31], EntityOtherPlayerMP['VcPandaMola'/33719309, l='MpServer', x=216.43, y=65.00, z=594.50], EntityOtherPlayerMP['Robo'/35769148, l='MpServer', x=219.01, y=65.00, z=600.85], EntityOtherPlayerMP['justjosbro'/34255350, l='MpServer', x=217.66, y=75.00, z=599.36], EntityOtherPlayerMP['Christian'/35595218, l='MpServer', x=241.97, y=65.00, z=596.69], EntityOtherPlayerMP['Ryukendo'/35311375, l='MpServer', x=243.91, y=65.00, z=592.97], EntityOtherPlayerMP['cool11012'/34817975, l='MpServer', x=245.91, y=65.00, z=598.00]]
	Chunk stats: MultiplayerChunkCache: 95, 95
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -403.00,84.00,-151.00 - World: (-403,84,-151), Chunk: (at 13,5,9 in -26,-10; contains blocks -416,0,-160 to -401,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 173596187 game time, 183564445 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntityPlayerSP['sidjaja'/35808272, l='MpServer', x=213.60, y=65.00, z=589.17], EntityOtherPlayerMP['Smichelle_01'/33903081, l='MpServer', x=233.16, y=65.00, z=596.25], EntityOtherPlayerMP['dodolgaratu'/35694995, l='MpServer', x=222.27, y=69.76, z=601.31], EntityOtherPlayerMP['VcPandaMola'/33719309, l='MpServer', x=216.43, y=65.00, z=594.50], EntityOtherPlayerMP['Robo'/35769148, l='MpServer', x=219.01, y=65.00, z=600.85], EntityOtherPlayerMP['cool11012'/34817975, l='MpServer', x=245.91, y=65.00, z=598.00], EntityDragon['§4V§6N§fI §6- §eInvite your Friend playing here'/35808614, l='MpServer', x=213.00, y=-235.00, z=589.00], EntityOtherPlayerMP['justjosbro'/34255350, l='MpServer', x=217.66, y=75.00, z=599.36], EntityOtherPlayerMP['Christian'/35595218, l='MpServer', x=241.97, y=65.00, z=596.69], EntityOtherPlayerMP['Ryukendo'/35311375, l='MpServer', x=243.91, y=65.00, z=592.97], EntityOcelot['§b§f§k:::§6Mi§9ku§f§k:::§r'/35808613, l='MpServer', x=245.94, y=65.00, z=598.00], EntityOtherPlayerMP['cool11012'/34817975, l='MpServer', x=245.91, y=65.00, z=598.00], EntityOtherPlayerMP['Smichelle_01'/33903081, l='MpServer', x=233.16, y=65.00, z=596.25], EntityOtherPlayerMP['Christian'/35595218, l='MpServer', x=241.97, y=65.00, z=596.69], EntityOtherPlayerMP['VcPandaMola'/33719309, l='MpServer', x=216.43, y=65.00, z=594.50], EntityOtherPlayerMP['dodolgaratu'/35694995, l='MpServer', x=222.27, y=69.76, z=601.31], EntityOtherPlayerMP['Ryukendo'/35311375, l='MpServer', x=243.91, y=65.00, z=592.97], EntityOtherPlayerMP['justjosbro'/34255350, l='MpServer', x=217.66, y=75.00, z=599.36], EntityOtherPlayerMP['Robo'/35769148, l='MpServer', x=219.01, y=65.00, z=600.85]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2921)
	at net.minecraft.client.Minecraft.run(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0 (latest: 2.0)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 190730408 bytes (181 MB) / 315514880 bytes (300 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3643, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
```

**Comment by billyoz** [comment]
What happen?

**Comment by mcccs** [comment]
Maybe i found the error:

  Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
