### ISSUE TITLE
Wurst Crashing whenever I try to open the new version

### ISSUE THREAD

**Issue by nkale1** [Wurst-Imperium/Wurst-Client#1180]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why is it breaking :(

Time: 7/10/15 10:05 AM
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 60150144 bytes (57 MB) / 281395200 bytes (268 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GTX 675MX OpenGL Engine GL version 2.1 NVIDIA-10.2.1 310.41.15f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [SC16-64 v27 - Place this in your resourcepacks folder WITHOUT extracting.zip, ImDaBestPack, ([1.7]_Huahwi_Pack_64x, xixSuPRem3xix CookieRanga]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Alexander01998** [comment]
You are not using Java 8.
