### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by sebstar2000** [Wurst-Imperium/Wurst-Client#1193]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Who set us up the TNT?

Time: 7/12/15 12:30 AM
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 105276472 bytes (100 MB) / 249069568 bytes (237 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.6.31, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by mcccs** [comment]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Who set us up the TNT?

Time: 7/12/15 12:30 AM
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
at tk.wurst_client.files.FileManager.init(FileManager.java:92)
at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
at net.minecraft.client.Minecraft.run(Minecraft.java:359)
at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
at tk.wurst_client.files.FileManager.init(FileManager.java:92)
at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.run(Minecraft.java:359)
at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
Minecraft Version: 1.8
Wurst Client Version: 2.0.1 (latest: unknown)
Operating System: Mac OS X (x86_64) version 10.10.4
Java Version: 1.6.0_65, Apple Inc.
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
Memory: 105276472 bytes (100 MB) / 249069568 bytes (237 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: Wurst
LWJGL: 2.9.2
OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.6.31, Intel Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
# *Duplicate: #142*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by sebstar2000** [comment]
I did but none of them had clear answers!
