### ISSUE TITLE
Crash....

### ISSUE THREAD

**Issue by natezoom** [Wurst-Imperium/Wurst-Client#1207]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// At least you got a nice looking crash report!

Time: 7/12/15 12:39 PM
Description: Initializing game

java.lang.NoClassDefFoundError: java/util/Base64
	at tk.wurst_client.alts.Encryption.encrypt(Encryption.java:61)
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)
Caused by: java.lang.ClassNotFoundException: java.util.Base64
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.alts.Encryption.encrypt(Encryption.java:61)
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Linux (i386) version 3.18.0-kali3-686-pae
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 99531496 bytes (94 MB) / 267726848 bytes (255 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 5 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Mesa DRI Intel(R) 965GM x86/MMX/SSE2 GL version 2.1 Mesa 8.0.5, Tungsten Graphics, Inc
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by GummiBoat** [comment]
# *Duplicate: #100*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by natezoom** [comment]
Mines different! Jeez

**Comment by bob80333** [comment]
Wurst requires java 8, and at the end of the crash report it says you have java 7 (1.7.0_79).

**Comment by OMGchangeMYusername** [comment]
Wow the outdated java issues are on a rampage just like optifine was... or close anyway.

**Comment by Alexander01998** [comment]
> Wow the outdated java issues are on a rampage just like optifine was... or close anyway.

Wurst 2.0 runs entirely on Java 8, so I can't display a custom error message to Java 6/7 users (a.k.a crApple users) anymore.
