### ISSUE TITLE
Killaura sg crash

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1214]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I let you down. Sorry :(

Time: 13.07.2015 13:11
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.util.ChatComponentStyle$1.apply(ChatComponentStyle.java:129)
	at net.minecraft.util.ChatComponentStyle$1.apply(ChatComponentStyle.java:133)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1158)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1294)
	at net.minecraft.client.Minecraft.run(Minecraft.java:379)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.util.ChatComponentStyle$1.apply(ChatComponentStyle.java:129)
	at net.minecraft.util.ChatComponentStyle$1.apply(ChatComponentStyle.java:133)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 13 total; [EntityPlayerSP['Notch_s_hero'/16234, l='MpServer', x=77,16, y=75,25, z=138,95], EntityOtherPlayerMP['GrishkaPlay'/66, l='MpServer', x=-5,16, y=78,08, z=145,56], EntityOtherPlayerMP['Naridral'/68, l='MpServer', x=-3,23, y=79,05, z=150,69], EntityOtherPlayerMP['tkopro'/71, l='MpServer', x=-21,56, y=70,09, z=121,65], EntityOtherPlayerMP['TheShooterYT'/72, l='MpServer', x=23,08, y=76,05, z=168,17], EntityOtherPlayerMP['iDeadly00'/80, l='MpServer', x=93,01, y=75,67, z=159,67], EntityOtherPlayerMP['minecraftpro8769'/81, l='MpServer', x=27,38, y=73,00, z=21,69], EntityOtherPlayerMP['DesertGryphon'/67, l='MpServer', x=8,36, y=67,00, z=107,18], EntityOtherPlayerMP['iWarriorHD'/64, l='MpServer', x=-28,38, y=73,00, z=53,00], EntityOtherPlayerMP['ShadowFighter_90'/60, l='MpServer', x=75,28, y=74,00, z=138,28], EntityOtherPlayerMP['Dervola'/78, l='MpServer', x=-54,38, y=70,42, z=46,84], EntityOtherPlayerMP['Novel_Killer'/76, l='MpServer', x=48,76, y=77,38, z=122,08], EntityOtherPlayerMP['TheD3athAng3l'/62, l='MpServer', x=80,29, y=76,07, z=148,72]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -1,00,77,00,1,00 - World: (-1,77,1), Chunk: (at 15,4,1 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6363270 game time, 312000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 40 total; [EntityOtherPlayerMP['iWarriorHD'/64, l='MpServer', x=-28,38, y=73,00, z=53,00], EntityOtherPlayerMP['GrishkaPlay'/66, l='MpServer', x=-5,16, y=78,08, z=145,56], EntityOtherPlayerMP['DesertGryphon'/67, l='MpServer', x=8,36, y=67,00, z=107,18], EntityOtherPlayerMP['Naridral'/68, l='MpServer', x=-3,23, y=79,05, z=150,69], EntityOtherPlayerMP['tkopro'/71, l='MpServer', x=-21,56, y=70,09, z=121,65], EntityOtherPlayerMP['TheShooterYT'/72, l='MpServer', x=23,08, y=76,05, z=168,17], EntityOtherPlayerMP['Notch_s_hero'/2147483647, l='MpServer', x=4,56, y=76,00, z=6,81], EntityOtherPlayerMP['Novel_Killer'/76, l='MpServer', x=48,76, y=77,38, z=122,08], EntityOtherPlayerMP['Notch_s_hero'/-69, l='MpServer', x=12,07, y=74,00, z=21,25], EntityOtherPlayerMP['Notch_s_hero'/-69, l='MpServer', x=12,39, y=75,25, z=21,89], EntityOtherPlayerMP['Dervola'/78, l='MpServer', x=-54,38, y=70,42, z=46,84], EntityOtherPlayerMP['Sitka_MC'/77, l='MpServer', x=136,48, y=107,30, z=-8,15], EntityOtherPlayerMP['TheD3athAng3l'/62, l='MpServer', x=80,29, y=76,07, z=148,72], EntityOtherPlayerMP['iDeadly00'/80, l='MpServer', x=93,01, y=75,67, z=159,67], EntityOtherPlayerMP['minecraftpro8769'/81, l='MpServer', x=27,38, y=73,00, z=21,69], EntityItem['item.item.helmetCloth'/94, l='MpServer', x=-47,94, y=73,00, z=37,34], EntityOtherPlayerMP['JaviiTalCual'/84, l='MpServer', x=-7,56, y=74,00, z=24,53], EntityOtherPlayerMP['tkopro'/71, l='MpServer', x=-21,56, y=70,09, z=121,65], EntityOtherPlayerMP['Naridral'/68, l='MpServer', x=-3,23, y=79,05, z=150,69], EntityOtherPlayerMP['NoHaxJustBatu'/74, l='MpServer', x=17,50, y=74,00, z=18,59], EntityOtherPlayerMP['GrishkaPlay'/66, l='MpServer', x=-5,16, y=78,08, z=145,56], EntityPlayerSP['Notch_s_hero'/16234, l='MpServer', x=77,16, y=75,25, z=138,95], EntityOtherPlayerMP['IIyIIceHb'/75, l='MpServer', x=12,50, y=74,00, z=-20,66], EntityOtherPlayerMP['Miko_Maz'/83, l='MpServer', x=-13,47, y=74,00, z=-20,00], EntityOtherPlayerMP['Cow3r'/82, l='MpServer', x=-21,78, y=73,04, z=56,64], EntityOtherPlayerMP['gokay003'/79, l='MpServer', x=-26,36, y=73,00, z=-48,34], EntityOtherPlayerMP['Novel_Killer'/76, l='MpServer', x=48,76, y=77,38, z=122,08], EntityOtherPlayerMP['xInFlamesx'/70, l='MpServer', x=8,48, y=72,42, z=-84,69], EntityOtherPlayerMP['CuzImDino_'/69, l='MpServer', x=36,27, y=72,00, z=54,75], EntityOtherPlayerMP['Dervola'/78, l='MpServer', x=-54,38, y=70,42, z=46,84], EntityOtherPlayerMP['VolvesTR'/73, l='MpServer', x=78,27, y=74,00, z=139,69], EntityOtherPlayerMP['ShadowFighter_90'/60, l='MpServer', x=75,28, y=74,00, z=138,28], EntityOtherPlayerMP['cubensis'/65, l='MpServer', x=-24,44, y=74,00, z=7,47], EntityOtherPlayerMP['iWarriorHD'/64, l='MpServer', x=-28,38, y=73,00, z=53,00], EntityOtherPlayerMP['DesertGryphon'/67, l='MpServer', x=8,36, y=67,00, z=107,18], EntityOtherPlayerMP['ShadowFighter_90'/60, l='MpServer', x=75,28, y=74,00, z=138,28], EntityOtherPlayerMP['minecraftpro8769'/81, l='MpServer', x=27,38, y=73,00, z=21,69], EntityOtherPlayerMP['iDeadly00'/80, l='MpServer', x=93,01, y=75,67, z=159,67], EntityOtherPlayerMP['TheD3athAng3l'/62, l='MpServer', x=80,29, y=76,07, z=148,72], EntityOtherPlayerMP['TheShooterYT'/72, l='MpServer', x=23,08, y=76,05, z=168,17]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"6dcd865":unknown) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2921)
	at net.minecraft.client.Minecraft.run(Minecraft.java:408)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: 2.0.1)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 670214432 bytes (639 MB) / 1731723264 bytes (1651 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7400M Series GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by GummiBoat** [comment]
# *Duplicate: #642*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
