### ISSUE TITLE
Freecam crash

### ISSUE THREAD

**Issue by Krowit** [Wurst-Imperium/Wurst-Client#124]
Hi, this is the error message I get when I use Freecam and the launcher crashes to a blackscreen.

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Daisy, daisy...

Time: 01.03.15 14:40
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockState{block=minecraft:double_stone_slab, properties=[seamless, variant]}
	at net.minecraft.block.state.BlockState$StateImplemenation.getValue(BlockState.java:150)
	at net.minecraft.world.World.doesBlockHaveSolidTopSurface(World.java:2422)
	at net.minecraft.block.BlockLiquid.randomDisplayTick(BlockLiquid.java:282)
	at net.minecraft.client.multiplayer.WorldClient.doVoidFogParticles(WorldClient.java:318)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2493)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1349)
	at net.minecraft.client.Minecraft.run(Minecraft.java:463)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplemenation.getValue(BlockState.java:150)
	at net.minecraft.world.World.doesBlockHaveSolidTopSurface(World.java:2422)
	at net.minecraft.block.BlockLiquid.randomDisplayTick(BlockLiquid.java:282)
	at net.minecraft.client.multiplayer.WorldClient.doVoidFogParticles(WorldClient.java:318)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Schimmelbrot'/1385, l='MpServer', x=807,69, y=199,68, z=-1233,76], EntityOtherPlayerMP['Schimmelbrot'/-69, l='MpServer', x=833,67, y=226,00, z=-1234,67]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 835,00,229,00,-1238,00 - World: (835,229,-1238), Chunk: (at 3,14,10 in 52,-78; contains blocks 832,0,-1248 to 847,255,-1233), Region: (1,-3; contains chunks 32,-96 to 63,-65, blocks 512,0,-1536 to 1023,255,-1025)
	Level time: 59022065 game time, 59158824 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 9 total; [EntityRabbit['Kaninchen'/846412, l='MpServer', x=820,66, y=76,00, z=-1201,91], EntityRabbit['Kaninchen'/846414, l='MpServer', x=849,72, y=68,00, z=-1202,91], EntityRabbit['Kaninchen'/846415, l='MpServer', x=864,66, y=65,00, z=-1207,75], EntityOtherPlayerMP['Schimmelbrot'/-69, l='MpServer', x=833,67, y=226,00, z=-1234,67], EntityChicken['Huhn'/846409, l='MpServer', x=856,31, y=76,00, z=-1226,44], EntityRabbit['Kaninchen'/846410, l='MpServer', x=836,38, y=92,00, z=-1260,50], EntityRabbit['Kaninchen'/846411, l='MpServer', x=854,16, y=63,00, z=-1256,53], EntityOtherPlayerMP['Schimmelbrot'/-69, l='MpServer', x=833,67, y=226,00, z=-1234,67], EntityPlayerSP['Schimmelbrot'/1385, l='MpServer', x=807,69, y=199,68, z=-1233,76]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"e1951c5":1050) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:3006)
	at net.minecraft.client.Minecraft.run(Minecraft.java:492)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.6.1 (latest: 1.6.1)
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 283811616 bytes (270 MB) / 1058537472 bytes (1009 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G
	IntCache: cache: 2, tcache: 43, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6900 Series GL version 4.2.12422 Compatibility Profile Context 13.152.0.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
> java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockState{**block=minecraft:double_stone_slab**, properties=[seamless, variant]}

Did you fly through a double stone slab block when this happened?

**Comment by Krowit** [comment]
No it crashes just a half second after activating so at this time I am in my player...
And just on special locations. I just tried Freecam randomly for testing and at some places it never crash and at other places it always crash.

**Comment by Alexander01998** [comment]
> And just on special locations. I just tried Freecam randomly for testing and at some places it never crash and at other places it always crash.

These "special locations" are definitely places where double stone slabs are nearby.

**Comment by Krowit** [comment]
possible due to Im testing it at a spawn right now...

**Comment by Krowit** [comment]
Yes the whole spawn's floor is out of double-stone-slabs.
But in some locations where also are these double-stone-slabs freecam don't crash.

**Comment by Alexander01998** [comment]
> Yes the whole spawn's floor is out of double-stone-slabs.
> But in some locations (also in the spawn) where these double-stone-slabs also are, Freecam doesn't crash.

That's a simple pattern: Fly through a double stone slab or stand on top of one and it crashes.

If I remember correctly, there has been a similar bug in Minecraft 1.7.

**Comment by Alexander01998** [comment]
Crash could not be reproduced. Tested with all 16 variants of double stone slabs.
![](https://cloud.githubusercontent.com/assets/10100202/6447804/c83fa068-c115-11e4-9704-403e1ff5b717.png)
