### ISSUE TITLE
Wurst crash when launched

### ISSUE THREAD

**Issue by Philamusant009** [Wurst-Imperium/Wurst-Client#1251]
I'm on mac

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Who set us up the TNT?

Time: 16/07/15 13:04
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 67217008 bytes (64 MB) / 255750144 bytes (243 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 640M OpenGL Engine GL version 2.1 NVIDIA-10.0.43 310.41.05f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by bob80333** [comment]
Oh look, its the daily "Mac user needs to update java" issue.
Update to java 8.
See issue #1224 for more information.

**Comment by Philamusant009** [comment]
Wow, very fast answer, thx ! Gonna try that ^^

**Comment by bob80333** [comment]
Thanks.  I get notifications on my phone so that's how I can respond faster (if I have service).

**Comment by Philamusant009** [comment]
Still not working :(

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Don't be sad. I'll do better next time, I promise!

Time: 16/07/15 14:58
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 72467304 bytes (69 MB) / 246464512 bytes (235 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 640M OpenGL Engine GL version 2.1 NVIDIA-10.0.43 310.41.05f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by bob80333** [comment]
```
Java Version: 1.6.0_65. Apple, Inc
 ```
Java is still outdated.  Did you try method #1 on the wiki linked in #1224?

**Comment by GummiBoat** [comment]
You didn't update your Java properly. As bob said, try using [this link](https://github.com/Wurst-Imperium/Wurst-Client/wiki/Using-Wurst-with-Java-8).

**Comment by Philamusant009** [comment]
Yes, gonna try #2

**Comment by Philamusant009** [comment]
I just used @GummiBoat link, but still isn't working ... It's like if java don't wanna update for minecraft, because when I do the "verify your java version" test, it's says it's up do date(Update 8.51)

```

```

**Comment by TekkitCommando** [comment]
Do you have jvm arguments in your minecraft launcher set to java 6

**Comment by Philamusant009** [comment]
Don't think so, how can I see if I have ??

**Comment by TekkitCommando** [comment]
Edit Profile -> see if jvm argument is checked an if it is it is enabled, see if its 1.6 that it's looking for

**Comment by Philamusant009** [comment]
No, my jam argument aren't enable.

**Comment by TekkitCommando** [comment]
Sorry not jvm arguments executable arguments
