### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Kris162CP** [Wurst-Imperium/Wurst-Client#1280]
Whenever I launch the YesCheat+ update, I get this error: 

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

I currently have Java 8 version 51, which is the latest version. I am on a Macbook Pro. Please help me ASAP!

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by Kris162CP** [comment]
This isn't the same issue! It's different, I have Java 8 Version 51. Even java verified that I have Java 8. THIS IS NOT THE SAME ISSUE AS #1224!

**Comment by Kris162CP** [comment]
http://prntscr.com/7u9v3y I am using Java 1.8, and I even reinstalled it. I did java -version in the terminal and it shows that I CLEARLY have 1.8. The bug that I reported is different from #1224. Please help.

**Comment by bob80333** [comment]
It has the same solution.  Download the minecraft.jar launcher from the minecraft website, as the installer version is outdated. Run it, and Wurst should work.

**Comment by Kris162CP** [comment]
I did that, and it still shows up the same error.

**Comment by bob80333** [comment]
The minecraft.jar from Linux/Others?

**Comment by Kris162CP** [comment]
Yes.
