### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by HeyImFanta** [Wurst-Imperium/Wurst-Client#1288]
I have the latest version of JAVA

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by bob80333** [comment]
The error is literally:
 ```
Unsupported minor version 52.0
 ```

**Comment by HeyImFanta** [comment]
How do i fix it then?

**Comment by bob80333** [comment]
Is that all of the crash report?  It would help to see the rest of it.

**Comment by HeyImFanta** [comment]
that is all
http://gyazo.com/0f3b9faa134e30ae86b440881a74f4b2

**Comment by bob80333** [comment]
Are you using the .jar version of the minecraft launcher?

**Comment by bob80333** [comment]
I found a similar issue.  Refer to issue #1224.

**Comment by HeyImFanta** [comment]
Bob, no or idk it says on the installer minecraft.dmg

**Comment by bob80333** [comment]
Specifically download the one called minecraft.jar from the website as it is more updated than the installer.  Just click/doubleclick it to run it.

**Comment by HeyImFanta** [comment]
okay

**Comment by HeyImFanta** [comment]
Dude thanks!
