### ISSUE TITLE
Game crashes at startup. What to do to run it?

### ISSUE THREAD

**Issue by HavanHUN** [Wurst-Imperium/Wurst-Client#1323]
```
java.io.FileNotFoundException: textures_0.png (A hozzáférés megtagadva)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at javax.imageio.stream.FileImageOutputStream.<init>(Unknown Source)
	at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(Unknown Source)
	at javax.imageio.ImageIO.createImageOutputStream(Unknown Source)
	at javax.imageio.ImageIO.write(Unknown Source)
	at net.minecraft.client.renderer.texture.TextureUtil.func_177055_a(TextureUtil.java:374)
	at net.minecraft.client.renderer.texture.TextureMap.loadTextureAtlas(TextureMap.java:278)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83)
	at net.minecraft.client.resources.model.ModelBakery.func_177572_j(ModelBakery.java:666)
	at net.minecraft.client.resources.model.ModelBakery.setupModelRegistry(ModelBakery.java:87)
	at net.minecraft.client.resources.model.ModelManager.onResourceManagerReload(ModelManager.java:26)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:514)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2015.07.20. 10:23
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at javax.imageio.ImageIO.write(Unknown Source)
	at net.minecraft.client.renderer.texture.TextureUtil.func_177055_a(TextureUtil.java:374)
	at net.minecraft.client.renderer.texture.TextureMap.loadTextureAtlas(TextureMap.java:278)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83)
	at net.minecraft.client.resources.model.ModelBakery.func_177572_j(ModelBakery.java:666)
	at net.minecraft.client.resources.model.ModelBakery.setupModelRegistry(ModelBakery.java:87)
	at net.minecraft.client.resources.model.ModelManager.onResourceManagerReload(ModelManager.java:26)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:514)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at javax.imageio.ImageIO.write(Unknown Source)
	at net.minecraft.client.renderer.texture.TextureUtil.func_177055_a(TextureUtil.java:374)
	at net.minecraft.client.renderer.texture.TextureMap.loadTextureAtlas(TextureMap.java:278)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83)
	at net.minecraft.client.resources.model.ModelBakery.func_177572_j(ModelBakery.java:666)
	at net.minecraft.client.resources.model.ModelBakery.setupModelRegistry(ModelBakery.java:87)
	at net.minecraft.client.resources.model.ModelManager.onResourceManagerReload(ModelManager.java:26)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:514)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: ~~ERROR~~ NullPointerException: null
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 110508992 bytes (105 MB) / 241508352 bytes (230 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 350.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [default3dmodelsv308872474.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Felhasználó\AppData\Roaming\.minecraft\crash-reports\crash-2015-07-20_10.23.34-client.txt
```

**Comment by HavanHUN** [comment]
Anyway the "Hozzáférés megtagadva" at the top means "Access denied". Previously wurst simply did not start. Now I reinstalled the latest java, and now starts but crash. What to do?????????????,

**Comment by Alexander01998** [comment]
May be because of your ResourcePack (default3dmodelsv308872474.zip).
