### ISSUE TITLE
Wurst crashes on launch

### ISSUE THREAD

**Issue by rmg099** [Wurst-Imperium/Wurst-Client#1343]
I updated my java to the most recent JDK version thinking it would fix this but it just crashes on launch with this error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

(Mac OSX Yosemite)

**Comment by WurstContributor** [comment]
Delete ur old version pf java

**Comment by rmg099** [comment]
i only have the one JDK file 
<img width="600" alt="screen shot 2015-07-21 at 9 14 00 pm" src="https://cloud.githubusercontent.com/assets/13443460/8815899/7e0e2ae0-2fed-11e5-839a-b6e09c34b58b.png">

**Comment by WurstContributor** [comment]
kk

**Comment by rmg099** [comment]
@WurstContributor Any other suggestions because it still crashes lol

**Comment by rmg099** [comment]
@Alexander01998 have you seen this before? any thoughts on what it could be?

**Comment by bob80333** [comment]
Are you using the minecraft.dmg installer for Mac as your launcher?  If that's the case, try using the minecraft.jar launcher on the downloads page.  Also, #1224 has a link to the wiki on updating java, try method 2.

**Comment by rmg099** [comment]
Im running the latest version of java as i said above, also the only available Minecraft download for Mac is the .dmg file.
@bob80333

**Comment by bob80333** [comment]
@rmg099
Click show all platforms, and under Linux/others is the minecraft.jar.  That is a more recent version and should fix your problem.

**Comment by rmg099** [comment]
@bob80333 Ayyyy that worked you're the man Bob

**Comment by OMGchangeMYusername** [comment]
Lol crApple users are retards xD (jk i swear)

**Comment by Bluscream** [comment]
föck cräpple

**Comment by Alexander01998** [comment]
:apple: = :shit:
