### ISSUE TITLE
Wust does not load!!!!!!!!

### ISSUE THREAD

**Issue by mybuttstinks** [Wurst-Imperium/Wurst-Client#1392]
I keep getting this error every time i try to load Wurst 
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

This message does not stop coming! It is an ∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞ message!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by JackFishbaugh** [comment]
upgrade java to the latest version. i believe it has been recently updated.

**Comment by JackFishbaugh** [comment]
and im sorry your butt stinks :(

**Comment by mybuttstinks** [comment]
JackFishBaugh 1 i already have updated java. 2 yes my butt stinks xD

**Comment by JackFishbaugh** [comment]
Are you sure you have the 64 bit version, installed Java correctly, and do you have an older version of Java installed along with the newer one. Also, try reinstalling Java. The error: 
'''
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
'''
Means that the version of Java you are using is not supported for the program you are opening. It could also be you butt odors. I recommend Febreze.

**Comment by OMGchangeMYusername** [comment]
um.. why did you start talking about butts anyway?

**Comment by mybuttstinks** [comment]
OMGchangeMYusername it is because my user is MYBUTTSTINKS!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by JackFishbaugh** [comment]
have you fixed it?

**Comment by LolDatSec** [comment]
https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md#issues exists for a reason bro. Also take a look at this: http://stackoverflow.com/questions/27143461/java-unsupported-major-minor-version-52-0-error-minecraft

 ` Unsupported major.minor version 52.0 ` 

Which more of less suggests to try upgrading your java version to Java-8.
If you are using a *nix distribution, try install openjdk-jre-8 and **remove previous versions** to prevent conflicts.
(And reboot afterwards for the OS level magic to happen.)

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
