### ISSUE TITLE
Crash on loading SP world

### ISSUE THREAD

**Issue by bob80333** [Wurst-Imperium/Wurst-Client#1402]
```
20:01:47.670 [Twitch authenticator] ERROR net.minecraft.client.stream.TwitchStream - Given twitch access token is invalid
javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:380)
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:291)
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2121)
	at tk.wurst_client.alts.Encryption.loadKeys(Encryption.java:221)
	at tk.wurst_client.alts.Encryption.checkKeys(Encryption.java:92)
	at tk.wurst_client.alts.Encryption.decrypt(Encryption.java:72)
	at tk.wurst_client.files.FileManager.loadAlts(FileManager.java:424)
	at tk.wurst_client.files.FileManager.init(FileManager.java:94)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)
java.lang.NullPointerException
	at tk.wurst_client.alts.Encryption.decrypt(Encryption.java:77)
	at tk.wurst_client.files.FileManager.loadAlts(FileManager.java:424)
	at tk.wurst_client.files.FileManager.init(FileManager.java:94)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at tk.wurst_client.files.FileManager.loadAlts(FileManager.java:423)
	at tk.wurst_client.files.FileManager.init(FileManager.java:94)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)
```

Caused when loading a new SP world.
Also, in options, in broadcast settings it says error with twitch, and offers a rebind account button.  Clicking on that causes a crash as well, but only with the twitch error at the top.

**Comment by bob80333** [comment]
Fixed by opening vanilla mc then reopening Wurst.
