### ISSUE TITLE
Wurst Crashes Instantly

### ISSUE THREAD

**Issue by cleveravi** [Wurst-Imperium/Wurst-Client#1417]
When I hit the "Play" button it crashes in a matter of seconds.
It says this:

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

Please fix this bug.

**Comment by bob80333** [comment]
Update your java to java 8.

**Comment by cleveravi** [comment]
I went to java control center and this is the version

Version 8 Update 51

**Comment by bob80333** [comment]
Are you on Mac?  If so, update your minecraft launcher.  Use the one for Linux, that should fix your problems.

**Comment by cleveravi** [comment]
Yes I'm on a mac, and where can I update my minecraft launcher with that specific requirment?

**Comment by OMGchangeMYusername** [comment]
minecraft.net/download

**Comment by cleveravi** [comment]
Thank you so very very much, I'm very happy now.

Thank you.
