### ISSUE TITLE
Cant add resource pack...

### ISSUE THREAD

**Issue by pankakePanda** [Wurst-Imperium/Wurst-Client#1420]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Shall we play a game?

Time: 7/29/15 11:56 AM
Description: Updating screen events

java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1348)
	at net.minecraft.client.renderer.texture.TextureUtil.func_177053_a(TextureUtil.java:319)
	at net.minecraft.client.resources.DefaultResourcePack.getPackImage(DefaultResourcePack.java:95)
	at net.minecraft.client.resources.ResourcePackListEntryDefault.<init>(ResourcePackListEntryDefault.java:29)
	at net.minecraft.client.gui.GuiScreenResourcePacks.initGui(GuiScreenResourcePacks.java:71)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:543)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1168)
	at net.minecraft.client.gui.GuiOptions.actionPerformed(GuiOptions.java:204)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at javax.imageio.ImageIO.read(ImageIO.java:1348)
	at net.minecraft.client.renderer.texture.TextureUtil.func_177053_a(TextureUtil.java:319)
	at net.minecraft.client.resources.DefaultResourcePack.getPackImage(DefaultResourcePack.java:95)
	at net.minecraft.client.resources.ResourcePackListEntryDefault.<init>(ResourcePackListEntryDefault.java:29)
	at net.minecraft.client.gui.GuiScreenResourcePacks.initGui(GuiScreenResourcePacks.java:71)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:543)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1168)
	at net.minecraft.client.gui.GuiOptions.actionPerformed(GuiOptions.java:204)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiScreenResourcePacks
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.1 (latest: 2.1)
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 164933008 bytes (157 MB) / 293625856 bytes (280 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by GummiBoat** [comment]
# *Duplicate: #1287*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
