### ISSUE TITLE
wurst crashing with message "suck my dick" if type .suckmydick

### ISSUE THREAD

**Issue by Th3C0ntr1but0r** [Wurst-Imperium/Wurst-Client#1487]
wurst crashing with message "suck my dick" if type .suckmydick

**Comment by mcccs** [comment]
please include crash report when reporting crashes,
And it's lie!
(Testing in minecraft not needed, just enter suck in the search bar)

**Comment by Th3C0ntr1but0r** [comment]
Crashreport:

Exception in thread "main" java.lang.UnsupportedClassPenisVersionError: net/minecraft/client/main/Main/Cock : Unsupported major.minor version 52.0
at java.lang.DickClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

Please fix this bug.

**Comment by GummiBoat** [comment]
Duplicate: #01110011011101010110001101101011011011010111100101100100011010010110001101101011

![687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67](https://cloud.githubusercontent.com/assets/10976441/9004724/ce18f456-3778-11e5-920e-26434fe323fd.png)
