### ISSUE TITLE
BUG I don't know how to fix. 

### ISSUE THREAD

**Issue by fweft** [Wurst-Imperium/Wurst-Client#1548]
There is an unknown bug i have 
 says:

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Also, I am a big fan of Wurst. I have been with you since the start!
Also please add optifine to next update

**Comment by GummiBoat** [comment]
# *Duplicate: #1224*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)
