### ISSUE TITLE
Outdated Java

### ISSUE THREAD

**Issue by smf01** [Wurst-Imperium/Wurst-Client#158]
I downloaded the Wurst Hacked Client 1.7, and when I try running Minecraft, it stops me and says "Your Java is outdated; get Java 8!!"
I do have the most recent Java: Java 8 update 40...
I'm on a Mac

**Comment by GlitchHead** [comment]
ok... goto terminal and type java -version
paste the output please.

**Comment by smf01** [comment]
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

**Comment by smf01** [comment]
Or there's this:
Exception in thread "main" java.lang.NoClassDefFoundError: version
Caused by: java.lang.ClassNotFoundException: version
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by Alexander01998** [comment]
Duplicate #142
