### ISSUE TITLE
Random Crash :P

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#1739]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Ooh. Shiny.

Time: 8/10/15 12:59 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.slotClick(Container.java:419)
	at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:551)
	at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:699)
	at net.minecraft.client.gui.inventory.GuiContainer.checkHotbarKeys(GuiContainer.java:740)
	at net.minecraft.client.gui.inventory.GuiContainer.keyTyped(GuiContainer.java:713)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:617)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:568)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.slotClick(Container.java:419)
	at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:551)
	at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:699)
	at net.minecraft.client.gui.inventory.GuiContainer.checkHotbarKeys(GuiContainer.java:740)
	at net.minecraft.client.gui.inventory.GuiContainer.keyTyped(GuiContainer.java:713)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:617)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:568)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	All players: 22 total; [EntityPlayerSP['Failvenom'/209907, l='MpServer', x=-2524.50, y=50.00, z=855.50], EntityOtherPlayerMP['ArriveChimera7'/145288, l='MpServer', x=-2526.09, y=51.00, z=857.06], EntityOtherPlayerMP['Dragongirl236'/146023, l='MpServer', x=-2518.94, y=50.00, z=849.28], EntityOtherPlayerMP['Kossio'/146009, l='MpServer', x=-2524.50, y=50.00, z=848.66], EntityOtherPlayerMP['NoNo259'/145969, l='MpServer', x=-2524.59, y=50.00, z=849.81], EntityOtherPlayerMP['TJM_68'/145929, l='MpServer', x=-2526.61, y=50.00, z=850.41], EntityOtherPlayerMP['Eze_The_Best'/145916, l='MpServer', x=-2522.47, y=50.00, z=855.63], EntityOtherPlayerMP['Gotenks0599'/145835, l='MpServer', x=-2528.22, y=50.00, z=844.50], EntityOtherPlayerMP['Zealock'/348, l='MpServer', x=-2521.50, y=50.00, z=842.50], EntityOtherPlayerMP['PokePancake'/146001, l='MpServer', x=-2525.34, y=50.00, z=841.34], EntityOtherPlayerMP['Buck240'/146005, l='MpServer', x=-2523.59, y=50.00, z=841.09], EntityOtherPlayerMP['Nic242rules'/145957, l='MpServer', x=-2524.50, y=48.00, z=835.50], EntityOtherPlayerMP['Troyan16'/145685, l='MpServer', x=-2522.53, y=51.00, z=838.97], EntityOtherPlayerMP['beach101'/144832, l='MpServer', x=-2482.72, y=47.00, z=849.00], EntityOtherPlayerMP['MeteDog'/145819, l='MpServer', x=-2524.31, y=4.95, z=801.22], EntityOtherPlayerMP['Jessek05'/145933, l='MpServer', x=-2524.41, y=45.00, z=810.03], EntityOtherPlayerMP['Lucadb'/145953, l='MpServer', x=-2447.47, y=55.41, z=844.22], EntityOtherPlayerMP['Colton2245'/145806, l='MpServer', x=-2591.25, y=70.00, z=827.22], EntityOtherPlayerMP['MyJade0609'/144864, l='MpServer', x=-2551.76, y=78.75, z=795.68], EntityOtherPlayerMP['warrior090904'/144356, l='MpServer', x=-2502.97, y=41.50, z=779.38], EntityOtherPlayerMP['ciol8991'/146015, l='MpServer', x=-2524.54, y=50.97, z=847.56], EntityOtherPlayerMP['3easy'/146027, l='MpServer', x=-2528.11, y=50.00, z=851.59]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -2525.00,50.00,855.00 - World: (-2525,50,855), Chunk: (at 3,3,7 in -158,53; contains blocks -2528,0,848 to -2513,255,863), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Level time: 227269686 game time, 534000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 63 total; [EntityOtherPlayerMP['Colton2245'/145806, l='MpServer', x=-2591.25, y=70.00, z=827.22], EntityOtherPlayerMP['Lucadb'/145953, l='MpServer', x=-2447.47, y=55.41, z=844.22], EntityOtherPlayerMP['warrior090904'/144356, l='MpServer', x=-2502.97, y=41.50, z=779.38], EntityOtherPlayerMP['MyJade0609'/144864, l='MpServer', x=-2551.76, y=78.75, z=795.68], EntityOtherPlayerMP['Jessek05'/145933, l='MpServer', x=-2524.41, y=45.00, z=810.03], EntityOtherPlayerMP['MeteDog'/145819, l='MpServer', x=-2524.31, y=4.95, z=801.22], EntityOtherPlayerMP['ArriveChimera7'/145288, l='MpServer', x=-2526.09, y=51.00, z=857.06], EntityOtherPlayerMP['TJM_68'/145929, l='MpServer', x=-2526.61, y=50.00, z=850.41], EntityOtherPlayerMP['Colton2245'/145806, l='MpServer', x=-2591.25, y=70.00, z=827.22], EntityOtherPlayerMP['3easy'/146027, l='MpServer', x=-2528.11, y=50.00, z=851.59], EntityOtherPlayerMP['ciol8991'/146015, l='MpServer', x=-2524.54, y=50.97, z=847.56], EntityOtherPlayerMP['Jessek05'/145933, l='MpServer', x=-2524.41, y=45.00, z=810.03], EntityOtherPlayerMP['Troyan16'/145685, l='MpServer', x=-2522.53, y=51.00, z=838.97], EntityOtherPlayerMP['MeteDog'/145819, l='MpServer', x=-2524.31, y=4.95, z=801.22], EntityOtherPlayerMP['Lucadb'/145953, l='MpServer', x=-2447.47, y=55.41, z=844.22], EntityOtherPlayerMP['Nic242rules'/145957, l='MpServer', x=-2524.50, y=48.00, z=835.50], EntityOtherPlayerMP['Gotenks0599'/145835, l='MpServer', x=-2528.22, y=50.00, z=844.50], EntityOtherPlayerMP['NoNo259'/145969, l='MpServer', x=-2524.59, y=50.00, z=849.81], EntityVillager['Villager'/186, l='MpServer', x=-2528.50, y=50.00, z=842.50], EntityItemFrame['entity.ItemFrame.name'/59, l='MpServer', x=-2549.03, y=14.50, z=829.50], EntityItemFrame['entity.ItemFrame.name'/60, l='MpServer', x=-2549.03, y=14.50, z=833.50], EntityOtherPlayerMP['beach101'/144832, l='MpServer', x=-2482.72, y=47.00, z=849.00], EntityArmorStand['§e§lParkour Challenge'/195, l='MpServer', x=-2468.50, y=51.34, z=843.50], EntityArmorStand['§a§lStart'/198, l='MpServer', x=-2468.50, y=51.00, z=843.50], EntityArmorStand['§e§lParkour Challenge'/201, l='MpServer', x=-2500.50, y=41.34, z=777.50], EntityArmorStand['§c§lEnd'/204, l='MpServer', x=-2500.50, y=41.00, z=777.50], EntityArmorStand['§e§lCheckpoint'/207, l='MpServer', x=-2393.50, y=47.34, z=836.50], EntityWither['§e§lLIMITED!§r §aUp to §c§l75% OFF §r§aeverything! §e? §bstore.hypixel.net'/-1234, l='MpServer', x=-2524.50, y=62.64, z=825.00], EntityArmorStand['§b§l#1'/210, l='MpServer', x=-2393.50, y=47.00, z=836.50], EntityPlayerSP['Failvenom'/209907, l='MpServer', x=-2524.50, y=50.00, z=855.50], EntityOtherPlayerMP['PokePancake'/146001, l='MpServer', x=-2525.34, y=50.00, z=841.34], EntityArmorStand['§e§lCheckpoint'/213, l='MpServer', x=-2397.50, y=47.34, z=774.50], EntityOtherPlayerMP['Buck240'/146005, l='MpServer', x=-2523.59, y=50.00, z=841.09], EntityArmorStand['§b§l#2'/216, l='MpServer', x=-2397.50, y=47.00, z=774.50], EntityArmorStand['§e§lCheckpoint'/219, l='MpServer', x=-2434.50, y=25.34, z=743.50], EntityOtherPlayerMP['Kossio'/146009, l='MpServer', x=-2524.50, y=50.00, z=848.66], EntityOtherPlayerMP['Zealock'/348, l='MpServer', x=-2521.50, y=50.00, z=842.50], EntityOtherPlayerMP['ciol8991'/146015, l='MpServer', x=-2524.54, y=50.97, z=847.56], EntityArmorStand['§b§l#3'/222, l='MpServer', x=-2434.50, y=25.00, z=743.50], EntityBat['Bat'/350, l='MpServer', x=-2521.50, y=51.35, z=842.50], EntityArmorStand['§e§lCheckpoint'/225, l='MpServer', x=-2512.50, y=43.34, z=746.50], EntityOtherPlayerMP['MyJade0609'/144864, l='MpServer', x=-2551.76, y=78.75, z=795.68], EntityArmorStand['§b§l#4'/228, l='MpServer', x=-2512.50, y=43.00, z=746.50], EntityOtherPlayerMP['Dragongirl236'/146023, l='MpServer', x=-2518.94, y=50.00, z=849.28], EntityOtherPlayerMP['warrior090904'/144356, l='MpServer', x=-2502.97, y=41.50, z=779.38], EntityArmorStand['§e§lCheckpoint'/231, l='MpServer', x=-2539.50, y=47.34, z=762.50], EntityOtherPlayerMP['Dragongirl236'/146023, l='MpServer', x=-2518.94, y=50.00, z=849.28], EntityOtherPlayerMP['3easy'/146027, l='MpServer', x=-2528.11, y=50.00, z=851.59], EntityArmorStand['§b§l#5'/234, l='MpServer', x=-2539.50, y=47.00, z=762.50], EntityOtherPlayerMP['NoNo259'/145969, l='MpServer', x=-2524.59, y=50.00, z=849.81], EntityOtherPlayerMP['Kossio'/146009, l='MpServer', x=-2524.50, y=50.00, z=848.66], EntityOtherPlayerMP['ArriveChimera7'/145288, l='MpServer', x=-2526.09, y=51.00, z=857.06], EntityOtherPlayerMP['Gotenks0599'/145835, l='MpServer', x=-2528.22, y=50.00, z=844.50], EntityIronGolem['Dinnerbone'/146035, l='MpServer', x=-2524.50, y=50.00, z=855.50], EntityOtherPlayerMP['Eze_The_Best'/145916, l='MpServer', x=-2522.47, y=50.00, z=855.63], EntityOtherPlayerMP['TJM_68'/145929, l='MpServer', x=-2526.61, y=50.00, z=850.41], EntityOtherPlayerMP['Nic242rules'/145957, l='MpServer', x=-2524.50, y=48.00, z=835.50], EntityOtherPlayerMP['Buck240'/146005, l='MpServer', x=-2523.59, y=50.00, z=841.09], EntityOtherPlayerMP['beach101'/144832, l='MpServer', x=-2482.72, y=47.00, z=849.00], EntityOtherPlayerMP['Troyan16'/145685, l='MpServer', x=-2522.53, y=51.00, z=838.97], EntityOtherPlayerMP['Zealock'/348, l='MpServer', x=-2521.50, y=50.00, z=842.50], EntityOtherPlayerMP['Eze_The_Best'/145916, l='MpServer', x=-2522.47, y=50.00, z=855.63], EntityOtherPlayerMP['PokePancake'/146001, l='MpServer', x=-2525.34, y=50.00, z=841.34]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.1 (latest: 2.1)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 175845408 bytes (167 MB) / 370188288 bytes (353 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 39, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by 1337HaxorKiddie** [comment]
Read the second line.

**Comment by WurstContributor** [comment]
@1337HaxorKiddie This is for reporting bugs *Facepalm*

**Comment by 1337HaxorKiddie** [comment]
I know.

**Comment by WurstContributor** [comment]
@1337HaxorKiddie Yes but what do you mean by read line 2? I read it.

**Comment by 1337HaxorKiddie** [comment]
Okay good.

**Comment by EnderGamer21** [comment]
.....⚉⚉......
⚉⚉⚉⚉⚉⚉
,,,,,,,,,,,,,,,,,,,,

**Comment by Alexander01998** [comment]
> Read the second line.

wurst-client.tk/bugs redirects here.

**Comment by Alexander01998** [comment]
What did you do just before this crash occurred?

**Comment by mcccs** [comment]
Maybe he went to mc.random.org server!

**Comment by ValenciaOrange** [comment]
I believe this is the texture pack crash

**Comment by 1337HaxorKiddie** [comment]
Yes, it seems like.

**Comment by WurstContributor** [comment]
Well I was playing a game and poof! Crashed!

**Comment by 1337HaxorKiddie** [comment]
I have sometimes the same Problem go on a Server with a texturepack after a few minutes my game is crashing. But only Ehen im using the texturepack.
