### ISSUE TITLE
Cant Open Game [Crash]

### ISSUE THREAD

**Issue by swagcat** [Wurst-Imperium/Wurst-Client#1769]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Quite honestly, I wouldn't worry myself about that.

Time: 8/12/15 2:11 AM
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.9.3
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 41992080 bytes (40 MB) / 293167104 bytes (279 MB) up to 1065025536 bytes (1015 MB)
	JVM Flags: 1 total; -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 640M OpenGL Engine GL version 2.1 NVIDIA-8.26.21 310.40.35f08, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [TheKiwiColonel #2]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Glowstone82** [comment]
Reeinstall Wurst
Delete the Wurst folder
and the Wurst folder in the versions folder

**Comment by Glowstone82** [comment]
and then download wurst agian

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
