### ISSUE TITLE
AutoArmor crashes when wearing heads or pumpkins

### ISSUE THREAD

**Issue by coolymike** [Wurst-Imperium/Wurst-Client#180]
crash wearing player heads
i shift clicked a  head and got a crash report
Report:
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Quite honestly, I wouldn't worry myself about that.

Time: 13-3-15 14:26
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.item.ItemSkull cannot be cast to net.minecraft.item.ItemArmor
	at tk.wurst_client.module.modules.AutoArmor.onUpdate(AutoArmor.java:59)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:140)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1887)
	at net.minecraft.world.World.updateEntity(World.java:1856)
	at net.minecraft.world.World.updateEntities(World.java:1705)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2451)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1350)
	at net.minecraft.client.Minecraft.run(Minecraft.java:464)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.module.modules.AutoArmor.onUpdate(AutoArmor.java:59)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:140)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1887)
	at net.minecraft.world.World.updateEntity(World.java:1856)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 399
	Entity Name: coolymike
	Entity's Exact location: 6108,10, 69,00, -2681,78
	Entity's Block location: 6108,00,69,00,-2682,00 - World: (6108,69,-2682), Chunk: (at 12,4,6 in 381,-168; contains blocks 6096,0,-2688 to 6111,255,-2673), Region: (11,-6; contains chunks 352,-192 to 383,-161, blocks 5632,0,-3072 to 6143,255,-2561)
	Entity's Momentum: 0,15, -0,08, 0,02
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1705)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['coolymike'/399, l='MpServer', x=6108,10, y=69,00, z=-2681,78], EntityOtherPlayerMP['ZiggyZaggy11'/2146035, l='MpServer', x=6108,97, y=69,00, z=-2679,84]]
	Chunk stats: MultiplayerChunkCache: 50, 50
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 3307,00,76,00,5295,00 - World: (3307,76,5295), Chunk: (at 11,4,15 in 206,330; contains blocks 3296,0,5280 to 3311,255,5295), Region: (6,10; contains chunks 192,320 to 223,351, blocks 3072,0,5120 to 3583,255,5631)
	Level time: 723277190 game time, 728215677 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 87 total; [EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPlayerSP['coolymike'/399, l='MpServer', x=6108,10, y=69,00, z=-2681,78], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityOtherPlayerMP['ZiggyZaggy11'/2146035, l='MpServer', x=6108,97, y=69,00, z=-2679,84], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityBat['Vleermuis'/7453663, l='MpServer', x=6140,22, y=13,41, z=-2688,13], EntityBat['Vleermuis'/7453662, l='MpServer', x=6143,75, y=14,10, z=-2699,25], EntityPainting['Schilderij'/2146599, l='MpServer', x=-2939,97, y=14,00, z=3055,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityOtherPlayerMP['coolymike'/-69, l='MpServer', x=-2916,70, y=12,00, z=3031,45], EntityItemFrame['entity.ItemFrame.name'/7452593, l='MpServer', x=6100,50, y=69,50, z=-2674,03], EntityWolf['milkywayz12's Wolf'/7452592, l='MpServer', x=6097,28, y=69,88, z=-2677,03], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityItemFrame['entity.ItemFrame.name'/7452577, l='MpServer', x=6100,50, y=69,50, z=-2685,97], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityItemFrame['entity.ItemFrame.name'/7452576, l='MpServer', x=6098,03, y=69,50, z=-2681,50], EntityItemFrame['entity.ItemFrame.name'/7452579, l='MpServer', x=6098,03, y=69,50, z=-2679,50], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityItemFrame['entity.ItemFrame.name'/7452578, l='MpServer', x=6098,03, y=69,50, z=-2675,50], EntityOtherPlayerMP['ZiggyZaggy11'/2146035, l='MpServer', x=6108,97, y=69,00, z=-2679,84], EntityItemFrame['entity.ItemFrame.name'/7452581, l='MpServer', x=6104,50, y=69,50, z=-2685,97], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityItemFrame['entity.ItemFrame.name'/7452580, l='MpServer', x=6098,03, y=69,50, z=-2682,50], EntityItemFrame['entity.ItemFrame.name'/7452583, l='MpServer', x=6099,50, y=69,50, z=-2685,97], EntityItemFrame['entity.ItemFrame.name'/7452582, l='MpServer', x=6098,03, y=69,50, z=-2677,50], EntityItemFrame['entity.ItemFrame.name'/7452585, l='MpServer', x=6098,03, y=69,50, z=-2674,50], EntityItemFrame['entity.ItemFrame.name'/7452584, l='MpServer', x=6099,50, y=69,50, z=-2674,03], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityItemFrame['entity.ItemFrame.name'/7452587, l='MpServer', x=6102,50, y=69,50, z=-2685,97], EntityItemFrame['entity.ItemFrame.name'/7452586, l='MpServer', x=6108,50, y=69,50, z=-2685,97], EntityItemFrame['entity.ItemFrame.name'/7452589, l='MpServer', x=6103,50, y=69,50, z=-2674,03], EntityItemFrame['entity.ItemFrame.name'/7452588, l='MpServer', x=6106,50, y=69,50, z=-2685,97], EntityItemFrame['entity.ItemFrame.name'/7452591, l='MpServer', x=6098,03, y=69,50, z=-2683,50], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityItemFrame['entity.ItemFrame.name'/7452590, l='MpServer', x=6101,50, y=69,50, z=-2685,97], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityItemFrame['entity.ItemFrame.name'/7452563, l='MpServer', x=6105,50, y=69,50, z=-2674,03], EntityItemFrame['entity.ItemFrame.name'/7452562, l='MpServer', x=6098,03, y=69,50, z=-2676,50], EntityItemFrame['entity.ItemFrame.name'/7452565, l='MpServer', x=6103,50, y=69,50, z=-2685,97], EntityItemFrame['entity.ItemFrame.name'/7452564, l='MpServer', x=6098,03, y=69,50, z=-2685,50], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityItemFrame['entity.ItemFrame.name'/7452567, l='MpServer', x=6098,50, y=69,50, z=-2685,97], EntityItemFrame['entity.ItemFrame.name'/7452566, l='MpServer', x=6098,03, y=69,50, z=-2680,50], EntityItemFrame['entity.ItemFrame.name'/7452569, l='MpServer', x=6107,50, y=69,50, z=-2685,97], EntityItemFrame['entity.ItemFrame.name'/7452568, l='MpServer', x=6098,50, y=69,50, z=-2674,03], EntityItemFrame['entity.ItemFrame.name'/7452571, l='MpServer', x=6106,50, y=69,50, z=-2674,03], EntityItemFrame['entity.ItemFrame.name'/7452570, l='MpServer', x=6104,50, y=69,50, z=-2674,03], EntityItemFrame['entity.ItemFrame.name'/7452573, l='MpServer', x=6107,50, y=69,50, z=-2674,03], EntityItemFrame['entity.ItemFrame.name'/7452572, l='MpServer', x=6098,03, y=69,50, z=-2678,50], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityItemFrame['entity.ItemFrame.name'/7452575, l='MpServer', x=6098,03, y=69,50, z=-2684,50], EntityItemFrame['entity.ItemFrame.name'/7452574, l='MpServer', x=6105,50, y=69,50, z=-2685,97], EntityPainting['Schilderij'/2146603, l='MpServer', x=-2939,97, y=14,00, z=3041,00], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00], EntityPainting['Schilderij'/2146711, l='MpServer', x=-2932,50, y=14,00, z=3025,03], EntityPainting['Schilderij'/2146701, l='MpServer', x=-2929,03, y=14,00, z=3063,00]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"f2d17cb":1052) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:3006)
	at net.minecraft.client.Minecraft.run(Minecraft.java:486)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.7 (latest: 1.7)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 274448736 bytes (261 MB) / 722518016 bytes (689 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [liedjes pack.zip, skelethond.zip]
	Current Language: Nederlands (Nederland)
	Profiler Position: N/A (disabled)
```

**Comment by Nitrogen-Dioxide** [comment]
so never put heads on your head .-. haha with autoarmor enabled.

**Comment by Alexander01998** [comment]
> so never put heads on your head .-. haha with autoarmor enabled.

Same with pumpkins.

**Comment by OMGchangeMYusername** [comment]
i have a weird question that's been worrying me since you said post crash reports.
the name....
if someone dosen't use alts (like me) posts a crash report here he will get banned the next day!
why? you reported a crash to hacked client thus we will frickin **ban** you.

**Comment by Alexander01998** [comment]
> if someone dosen't use alts (like me) posts a crash report here he will get banned the next day!
> why? you reported a crash to hacked client thus we will frickin ban you.

Almost no server owner does that because it's not at all worth it. You will certainly **not** get banned from Mineplex after one day. If at all, you might get banned from `93.200.208.99` after one month.

If you are still worried about this, you can always censor out the name and then post the crash report.

**Comment by OMGchangeMYusername** [comment]
>you will certainly not get banned from Mineplex after one day. If at all, you might get banned from 93.200.208.99 after one month.

well i didn't precisely worry about myself. 
but what makes you sure that Wurst client (which has been downloaded idk thousand times) won't make servers do that?
>you can always censor out the name and then post the crash report.

that's what i thought of the instant i replied :stuck_out_tongue_winking_eye: but i was like never mind..

**Comment by Alexander01998** [comment]
> but what makes you sure that Wurst client (which has been downloaded idk thousand times) won't make servers do that?

Because each crash report only contains one username and there aren't too many crash reports out there. This repo, which only contains ~10 crash reports, is pretty much the only place where the crash reports are well organized and easy to see, all the other ones are scattered across the internet and almost impossible to find.

> which has been downloaded idk thousand times

According to Google Analytics, it has been downloaded about 175000 times. I'm planning to integrate Google Analytics directly into the client to get some more accurate numbers.
