### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#1803]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 8/13/15 7:08 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraft.network.NetworkManager$InboundHandlerTuplePacketListener.access$0(NetworkManager.java:454)
	at net.minecraft.network.NetworkManager.flushOutboundQueue(NetworkManager.java:251)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:260)
	at net.minecraft.client.multiplayer.GuiConnecting.updateScreen(GuiConnecting.java:115)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1964)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.network.NetworkManager$InboundHandlerTuplePacketListener.access$0(NetworkManager.java:454)
	at net.minecraft.network.NetworkManager.flushOutboundQueue(NetworkManager.java:251)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:260)
	at net.minecraft.client.multiplayer.GuiConnecting.updateScreen(GuiConnecting.java:115)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1964)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.1 (latest: 2.1)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 192305592 bytes (183 MB) / 302891008 bytes (288 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled) 
```

**Comment by EnderGamer21** [comment]
try restrating ur client or try running the version first inb a a non hacked client then go to wurst client

**Comment by Alexander01998** [comment]
What did you do just before the crash occurred? Does it still happen in Wurst 2.2?

**Comment by WurstContributor** [comment]
I joined a server the Kabem! Crash.

**Comment by WurstContributor** [comment]
Wurst 2.2 I tried getting it to crash and did but it didnt print a crash log.

**Comment by solidshadow96** [comment]
what is da server ip :P

**Comment by WurstContributor** [comment]
mc.hypixel.net

**Comment by solidshadow96** [comment]
rlly hypixel made u crash try a single player game and see if you have nuker on also try using panic

**Comment by WurstContributor** [comment]
I didn't have nuker enabled.

**Comment by solidshadow96** [comment]
is it working now
?

**Comment by WurstContributor** [comment]
It was a rare random crash. I've tried replicating it.

**Comment by Alexander01998** [comment]
Seems like Minecraft had a problem with the packets that Hypixel sent to it. Might be a vanilla bug.
