### ISSUE TITLE
Touch Screen Inventory Crash

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1878]
When you take an item and move it somewhere in your inventory, while touch screen mode is enabled, your game crashes. (I know how to do the markdown thing: I just put <code>```</code> before and after it.)

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why is it breaking :(

Time: 8/17/15 3:01 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:39)
	at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:370)
	at net.minecraft.client.gui.inventory.GuiContainer.drawItemStack(GuiContainer.java:212)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:188)
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:50)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:636)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1180)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1298)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:39)
	at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:370)
	at net.minecraft.client.gui.inventory.GuiContainer.drawItemStack(GuiContainer.java:212)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:188)
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:50)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:636)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (192, 136). Absolute: (384, 207)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Instictive'/6, l='MpServer', x=-327.62, y=55.00, z=-1131.46]]
	Chunk stats: MultiplayerChunkCache: 2400, 2400
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -342.00,4.00,-1121.00 - World: (-342,4,-1121), Chunk: (at 10,0,15 in -22,-71; contains blocks -352,0,-1136 to -337,255,-1121), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
	Level time: 18647 game time, 18647 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 53 total; [EntityArmorStand['bp'/0, l='MpServer', x=-360.25, y=56.00, z=-1128.34], EntitySpider['Spider'/477317, l='MpServer', x=-338.50, y=56.00, z=-1192.50], EntityArmorStand['rp'/3, l='MpServer', x=-351.22, y=56.00, z=-1138.53], EntityCreeper['Creeper'/454917, l='MpServer', x=-292.50, y=56.00, z=-1159.50], EntitySpider['Spider'/477316, l='MpServer', x=-342.50, y=56.00, z=-1194.19], EntityArmorStand['delete'/4, l='MpServer', x=-338.50, y=63.50, z=-1131.50], EntityEnderman['Enderman'/454914, l='MpServer', x=-298.50, y=56.00, z=-1161.50], EntityPlayerSP['Instictive'/6, l='MpServer', x=-327.62, y=55.00, z=-1131.46], EntitySkeleton['Skeleton'/334338, l='MpServer', x=-336.22, y=56.00, z=-1106.28], EntitySpider['Spider'/365314, l='MpServer', x=-343.50, y=56.00, z=-1086.50], EntityZombie['Zombie'/472853, l='MpServer', x=-328.19, y=56.00, z=-1061.38], EntityZombie['Zombie'/398992, l='MpServer', x=-394.66, y=56.00, z=-1120.66], EntityZombie['Zombie'/472858, l='MpServer', x=-315.50, y=56.00, z=-1060.50], EntityZombie['Zombie'/472857, l='MpServer', x=-315.50, y=56.00, z=-1061.50], EntityZombie['Zombie'/472856, l='MpServer', x=-314.50, y=56.00, z=-1055.50], EntitySpider['Spider'/399014, l='MpServer', x=-401.84, y=56.00, z=-1051.22], EntityCreeper['Creeper'/472867, l='MpServer', x=-267.19, y=56.00, z=-1117.84], EntitySpider['Spider'/399011, l='MpServer', x=-390.50, y=56.00, z=-1053.50], EntityCreeper['Creeper'/472866, l='MpServer', x=-260.50, y=56.00, z=-1132.84], EntitySkeleton['Skeleton'/430254, l='MpServer', x=-292.81, y=56.00, z=-1120.25], EntityCreeper['Creeper'/399020, l='MpServer', x=-258.00, y=56.00, z=-1155.66], EntityCreeper['Creeper'/430253, l='MpServer', x=-319.97, y=56.00, z=-1118.84], EntityCreeper['Creeper'/330027, l='MpServer', x=-355.09, y=56.00, z=-1151.63], EntityZombie['Zombie'/422579, l='MpServer', x=-256.78, y=56.00, z=-1102.66], EntitySpider['Spider'/265660, l='MpServer', x=-354.94, y=56.00, z=-1108.56], EntitySpider['Spider'/480828, l='MpServer', x=-335.50, y=56.00, z=-1091.50], EntitySpider['Spider'/265658, l='MpServer', x=-315.41, y=56.00, z=-1101.16], EntitySpider['Spider'/447288, l='MpServer', x=-372.50, y=56.00, z=-1165.50], EntitySpider['Spider'/265659, l='MpServer', x=-362.28, y=56.00, z=-1118.69], EntitySkeleton['Skeleton'/422585, l='MpServer', x=-250.50, y=56.00, z=-1101.50], EntityCreeper['Creeper'/480832, l='MpServer', x=-337.22, y=56.00, z=-1092.94], EntityCreeper['Creeper'/458063, l='MpServer', x=-349.50, y=56.00, z=-1100.50], EntityCreeper['Creeper'/458061, l='MpServer', x=-348.50, y=56.00, z=-1100.50], EntitySkeleton['Skeleton'/378839, l='MpServer', x=-333.31, y=56.00, z=-1135.91], EntitySkeleton['Skeleton'/437973, l='MpServer', x=-384.50, y=56.00, z=-1064.50], EntitySkeleton['Skeleton'/430290, l='MpServer', x=-358.50, y=56.00, z=-1159.50], EntitySpider['Spider'/437970, l='MpServer', x=-386.50, y=56.00, z=-1066.50], EntitySkeleton['Skeleton'/430289, l='MpServer', x=-358.50, y=56.00, z=-1156.50], EntitySpider['Spider'/480863, l='MpServer', x=-258.50, y=56.00, z=-1130.50], EntitySpider['Spider'/372197, l='MpServer', x=-383.50, y=56.00, z=-1208.50], EntityCreeper['Creeper'/480868, l='MpServer', x=-262.50, y=56.00, z=-1132.50], EntitySpider['Spider'/480864, l='MpServer', x=-260.50, y=56.00, z=-1131.03], EntitySpider['Spider'/466798, l='MpServer', x=-332.78, y=56.00, z=-1103.19], EntitySkeleton['Skeleton'/458093, l='MpServer', x=-285.28, y=56.00, z=-1121.75], EntitySpider['Spider'/466794, l='MpServer', x=-270.50, y=56.00, z=-1064.50], EntityZombie['Zombie'/480873, l='MpServer', x=-342.50, y=56.00, z=-1196.00], EntityCreeper['Creeper'/458089, l='MpServer', x=-289.06, y=56.00, z=-1127.31], EntityZombie['Zombie'/480872, l='MpServer', x=-340.59, y=56.00, z=-1191.88], EntityCreeper['Creeper'/458100, l='MpServer', x=-269.97, y=56.00, z=-1127.28], EntityCreeper['Creeper'/477301, l='MpServer', x=-292.50, y=56.00, z=-1068.50], EntityCreeper['Creeper'/466802, l='MpServer', x=-332.50, y=56.00, z=-1094.50], EntitySpider['Spider'/477311, l='MpServer', x=-341.38, y=56.00, z=-1184.16], EntitySkeleton['Skeleton'/365311, l='MpServer', x=-360.16, y=56.00, z=-1099.28]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.2 (latest: 2.2)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 319279872 bytes (304 MB) / 907218944 bytes (865 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by mcccs** [comment]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why is it breaking :(

Time: 8/17/15 3:01 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:39)
at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:370)
at net.minecraft.client.gui.inventory.GuiContainer.drawItemStack(GuiContainer.java:212)
at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:188)
at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:50)
at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:636)
at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1180)
at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1298)
at net.minecraft.client.Minecraft.run(Minecraft.java:383)
at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at net.minecraft.client.renderer.ItemModelMesher.getItemModel(ItemModelMesher.java:39)
at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:370)
at net.minecraft.client.gui.inventory.GuiContainer.drawItemStack(GuiContainer.java:212)
at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:188)
at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:50)
at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:636)

-- Screen render details --
Details:
Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
Mouse location: Scaled: (192, 136). Absolute: (384, 207)
Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['Instictive'/6, l='MpServer', x=-327.62, y=55.00, z=-1131.46]]
Chunk stats: MultiplayerChunkCache: 2400, 2400
Level seed: 0
Level generator: ID 01 - flat, ver 0. Features enabled: false
Level generator options: 
Level spawn location: -342.00,4.00,-1121.00 - World: (-342,4,-1121), Chunk: (at 10,0,15 in -22,-71; contains blocks -352,0,-1136 to -337,255,-1121), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
Level time: 18647 game time, 18647 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 53 total; [EntityArmorStand['bp'/0, l='MpServer', x=-360.25, y=56.00, z=-1128.34], EntitySpider['Spider'/477317, l='MpServer', x=-338.50, y=56.00, z=-1192.50], EntityArmorStand['rp'/3, l='MpServer', x=-351.22, y=56.00, z=-1138.53], EntityCreeper['Creeper'/454917, l='MpServer', x=-292.50, y=56.00, z=-1159.50], EntitySpider['Spider'/477316, l='MpServer', x=-342.50, y=56.00, z=-1194.19], EntityArmorStand['delete'/4, l='MpServer', x=-338.50, y=63.50, z=-1131.50], EntityEnderman['Enderman'/454914, l='MpServer', x=-298.50, y=56.00, z=-1161.50], EntityPlayerSP['Instictive'/6, l='MpServer', x=-327.62, y=55.00, z=-1131.46], EntitySkeleton['Skeleton'/334338, l='MpServer', x=-336.22, y=56.00, z=-1106.28], EntitySpider['Spider'/365314, l='MpServer', x=-343.50, y=56.00, z=-1086.50], EntityZombie['Zombie'/472853, l='MpServer', x=-328.19, y=56.00, z=-1061.38], EntityZombie['Zombie'/398992, l='MpServer', x=-394.66, y=56.00, z=-1120.66], EntityZombie['Zombie'/472858, l='MpServer', x=-315.50, y=56.00, z=-1060.50], EntityZombie['Zombie'/472857, l='MpServer', x=-315.50, y=56.00, z=-1061.50], EntityZombie['Zombie'/472856, l='MpServer', x=-314.50, y=56.00, z=-1055.50], EntitySpider['Spider'/399014, l='MpServer', x=-401.84, y=56.00, z=-1051.22], EntityCreeper['Creeper'/472867, l='MpServer', x=-267.19, y=56.00, z=-1117.84], EntitySpider['Spider'/399011, l='MpServer', x=-390.50, y=56.00, z=-1053.50], EntityCreeper['Creeper'/472866, l='MpServer', x=-260.50, y=56.00, z=-1132.84], EntitySkeleton['Skeleton'/430254, l='MpServer', x=-292.81, y=56.00, z=-1120.25], EntityCreeper['Creeper'/399020, l='MpServer', x=-258.00, y=56.00, z=-1155.66], EntityCreeper['Creeper'/430253, l='MpServer', x=-319.97, y=56.00, z=-1118.84], EntityCreeper['Creeper'/330027, l='MpServer', x=-355.09, y=56.00, z=-1151.63], EntityZombie['Zombie'/422579, l='MpServer', x=-256.78, y=56.00, z=-1102.66], EntitySpider['Spider'/265660, l='MpServer', x=-354.94, y=56.00, z=-1108.56], EntitySpider['Spider'/480828, l='MpServer', x=-335.50, y=56.00, z=-1091.50], EntitySpider['Spider'/265658, l='MpServer', x=-315.41, y=56.00, z=-1101.16], EntitySpider['Spider'/447288, l='MpServer', x=-372.50, y=56.00, z=-1165.50], EntitySpider['Spider'/265659, l='MpServer', x=-362.28, y=56.00, z=-1118.69], EntitySkeleton['Skeleton'/422585, l='MpServer', x=-250.50, y=56.00, z=-1101.50], EntityCreeper['Creeper'/480832, l='MpServer', x=-337.22, y=56.00, z=-1092.94], EntityCreeper['Creeper'/458063, l='MpServer', x=-349.50, y=56.00, z=-1100.50], EntityCreeper['Creeper'/458061, l='MpServer', x=-348.50, y=56.00, z=-1100.50], EntitySkeleton['Skeleton'/378839, l='MpServer', x=-333.31, y=56.00, z=-1135.91], EntitySkeleton['Skeleton'/437973, l='MpServer', x=-384.50, y=56.00, z=-1064.50], EntitySkeleton['Skeleton'/430290, l='MpServer', x=-358.50, y=56.00, z=-1159.50], EntitySpider['Spider'/437970, l='MpServer', x=-386.50, y=56.00, z=-1066.50], EntitySkeleton['Skeleton'/430289, l='MpServer', x=-358.50, y=56.00, z=-1156.50], EntitySpider['Spider'/480863, l='MpServer', x=-258.50, y=56.00, z=-1130.50], EntitySpider['Spider'/372197, l='MpServer', x=-383.50, y=56.00, z=-1208.50], EntityCreeper['Creeper'/480868, l='MpServer', x=-262.50, y=56.00, z=-1132.50], EntitySpider['Spider'/480864, l='MpServer', x=-260.50, y=56.00, z=-1131.03], EntitySpider['Spider'/466798, l='MpServer', x=-332.78, y=56.00, z=-1103.19], EntitySkeleton['Skeleton'/458093, l='MpServer', x=-285.28, y=56.00, z=-1121.75], EntitySpider['Spider'/466794, l='MpServer', x=-270.50, y=56.00, z=-1064.50], EntityZombie['Zombie'/480873, l='MpServer', x=-342.50, y=56.00, z=-1196.00], EntityCreeper['Creeper'/458089, l='MpServer', x=-289.06, y=56.00, z=-1127.31], EntityZombie['Zombie'/480872, l='MpServer', x=-340.59, y=56.00, z=-1191.88], EntityCreeper['Creeper'/458100, l='MpServer', x=-269.97, y=56.00, z=-1127.28], EntityCreeper['Creeper'/477301, l='MpServer', x=-292.50, y=56.00, z=-1068.50], EntityCreeper['Creeper'/466802, l='MpServer', x=-332.50, y=56.00, z=-1094.50], EntitySpider['Spider'/477311, l='MpServer', x=-341.38, y=56.00, z=-1184.16], EntitySkeleton['Skeleton'/365311, l='MpServer', x=-360.16, y=56.00, z=-1099.28]]
Retry entities: 0 total; []
Server brand: vanilla
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
at net.minecraft.client.Minecraft.run(Minecraft.java:405)
at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
Minecraft Version: 1.8
Wurst Client Version: 2.2 (latest: 2.2)
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 319279872 bytes (304 MB) / 907218944 bytes (865 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: Wurst
LWJGL: 2.9.1
OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by GummiBoat** [comment]
But it works on my machine!

![bug](https://cloud.githubusercontent.com/assets/10976441/9306134/b44757d0-44f6-11e5-8095-0698a953e8ea.gif)

**Comment by JackFishbaugh** [comment]
you have to actually not just put in in an empty slot, but put it somewhere that has another block of a different type. like this..

https://i.gyazo.com/7fa0b9a765a7837e439163c8c6c6b81b.gif
