### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by RaiderzFtw** [Wurst-Imperium/Wurst-Client#1879]
So sometimes I crash when using Wurst. and I kept getting this message when I crash "Please this at http://www.github.com/Wurst-Imperium/Wurst-Cilent/issues so here's what it said

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// You're mean.

Time: 8/18/15 5:56 AM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 0
	at tk.wurst_client.options.gui.GuiKeybindManager.actionPerformed(GuiKeybindManager.java:84)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiKeybindManager.mouseClicked(GuiKeybindManager.java:118)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.options.gui.GuiKeybindManager.actionPerformed(GuiKeybindManager.java:84)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiKeybindManager.mouseClicked(GuiKeybindManager.java:118)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: tk.wurst_client.options.gui.GuiKeybindManager

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RaiderzFtw'/266, l='MpServer', x=436.06, y=62.00, z=183.95]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 204.00,64.00,256.00 - World: (204,64,256), Chunk: (at 12,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 66438 game time, 49916 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 45 total; [EntityCow['Cow'/256, l='MpServer', x=392.50, y=70.00, z=232.50], EntityCow['Cow'/257, l='MpServer', x=388.22, y=68.00, z=241.34], EntityZombie['Zombie'/270, l='MpServer', x=420.56, y=62.40, z=214.19], EntityCow['Cow'/271, l='MpServer', x=405.53, y=74.00, z=252.28], EntityCow['Cow'/272, l='MpServer', x=413.94, y=66.00, z=246.13], EntityPlayerSP['RaiderzFtw'/266, l='MpServer', x=436.06, y=62.00, z=183.95], EntityCow['Cow'/279, l='MpServer', x=420.09, y=63.00, z=123.13], EntityCow['Cow'/280, l='MpServer', x=428.69, y=64.00, z=142.44], EntityCow['Cow'/284, l='MpServer', x=422.72, y=61.00, z=250.53], EntityCow['Cow'/285, l='MpServer', x=423.81, y=61.00, z=249.13], EntityZombie['Zombie'/2338, l='MpServer', x=358.50, y=25.00, z=252.50], EntityCow['Cow'/291, l='MpServer', x=426.25, y=63.00, z=207.53], EntityCow['Cow'/292, l='MpServer', x=442.56, y=63.00, z=234.53], EntityCow['Cow'/293, l='MpServer', x=427.09, y=66.00, z=232.03], EntityCreeper['Creeper'/1448, l='MpServer', x=436.38, y=36.00, z=264.97], EntityCow['Cow'/297, l='MpServer', x=460.75, y=62.00, z=117.22], EntityCow['Cow'/298, l='MpServer', x=459.94, y=65.00, z=116.84], EntityCow['Cow'/299, l='MpServer', x=445.34, y=65.00, z=121.50], EntityCow['Cow'/300, l='MpServer', x=451.69, y=63.00, z=139.53], EntityCow['Cow'/301, l='MpServer', x=453.78, y=63.00, z=134.81], EntityCow['Cow'/304, l='MpServer', x=456.25, y=63.00, z=145.47], EntityCow['Cow'/311, l='MpServer', x=458.38, y=67.00, z=237.34], EntityBat['Bat'/2106, l='MpServer', x=371.25, y=30.10, z=176.25], EntityEnderman['Enderman'/2236, l='MpServer', x=430.50, y=32.00, z=106.50], EntityBat['Bat'/2111, l='MpServer', x=413.26, y=39.06, z=122.67], EntityCow['Cow'/320, l='MpServer', x=479.28, y=64.00, z=116.19], EntityItem['item.item.rottenFlesh'/1235, l='MpServer', x=453.28, y=64.00, z=201.50], EntityItem['item.item.rottenFlesh'/1239, l='MpServer', x=433.34, y=67.00, z=237.34], EntityBat['Bat'/2651, l='MpServer', x=438.33, y=36.82, z=105.79], EntityBat['Bat'/1372, l='MpServer', x=418.25, y=28.10, z=242.75], EntityVillager['Villager'/232, l='MpServer', x=368.28, y=93.00, z=120.69], EntityZombie['Zombie'/2541, l='MpServer', x=492.50, y=44.00, z=121.50], EntitySkeleton['Skeleton'/2542, l='MpServer', x=495.50, y=44.00, z=121.50], EntityFallingBlock['Falling Block'/371, l='MpServer', x=553.50, y=16.65, z=319.50], EntityFallingBlock['Falling Block'/372, l='MpServer', x=554.50, y=17.65, z=319.50], EntityFallingBlock['Falling Block'/373, l='MpServer', x=553.50, y=16.65, z=319.50], EntityXPOrb['Experience Orb'/2549, l='MpServer', x=433.68, y=62.00, z=181.63], EntityFallingBlock['Falling Block'/374, l='MpServer', x=554.50, y=17.94, z=319.50], EntityFallingBlock['Falling Block'/375, l='MpServer', x=553.50, y=16.94, z=319.50], EntityFallingBlock['Falling Block'/376, l='MpServer', x=554.50, y=17.94, z=319.50], EntityEnderman['Enderman'/1657, l='MpServer', x=369.50, y=33.00, z=223.50], EntityCow['Cow'/253, l='MpServer', x=392.13, y=70.00, z=221.81], EntityBat['Bat'/1533, l='MpServer', x=364.69, y=15.00, z=166.50], EntityCreeper['Creeper'/1790, l='MpServer', x=371.50, y=26.00, z=223.50], EntityCow['Cow'/255, l='MpServer', x=399.31, y=70.00, z=233.59]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.2 (latest: 2.2)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 194245864 bytes (185 MB) / 584777728 bytes (557 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Huahwi_Edited_Defscape.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
So sometimes I crash when using Wurst. and I kept getting this message when I crash "Please this at http://www.github.com/Wurst-Imperium/Wurst-Cilent/issues so here's what it said ---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// You're mean.

Time: 8/18/15 5:56 AM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 0
	at tk.wurst_client.options.gui.GuiKeybindManager.actionPerformed(GuiKeybindManager.java:84)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiKeybindManager.mouseClicked(GuiKeybindManager.java:118)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.options.gui.GuiKeybindManager.actionPerformed(GuiKeybindManager.java:84)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiKeybindManager.mouseClicked(GuiKeybindManager.java:118)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: tk.wurst_client.options.gui.GuiKeybindManager

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RaiderzFtw'/266, l='MpServer', x=436.06, y=62.00, z=183.95]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 204.00,64.00,256.00 - World: (204,64,256), Chunk: (at 12,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 66438 game time, 49916 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 45 total; [EntityCow['Cow'/256, l='MpServer', x=392.50, y=70.00, z=232.50], EntityCow['Cow'/257, l='MpServer', x=388.22, y=68.00, z=241.34], EntityZombie['Zombie'/270, l='MpServer', x=420.56, y=62.40, z=214.19], EntityCow['Cow'/271, l='MpServer', x=405.53, y=74.00, z=252.28], EntityCow['Cow'/272, l='MpServer', x=413.94, y=66.00, z=246.13], EntityPlayerSP['RaiderzFtw'/266, l='MpServer', x=436.06, y=62.00, z=183.95], EntityCow['Cow'/279, l='MpServer', x=420.09, y=63.00, z=123.13], EntityCow['Cow'/280, l='MpServer', x=428.69, y=64.00, z=142.44], EntityCow['Cow'/284, l='MpServer', x=422.72, y=61.00, z=250.53], EntityCow['Cow'/285, l='MpServer', x=423.81, y=61.00, z=249.13], EntityZombie['Zombie'/2338, l='MpServer', x=358.50, y=25.00, z=252.50], EntityCow['Cow'/291, l='MpServer', x=426.25, y=63.00, z=207.53], EntityCow['Cow'/292, l='MpServer', x=442.56, y=63.00, z=234.53], EntityCow['Cow'/293, l='MpServer', x=427.09, y=66.00, z=232.03], EntityCreeper['Creeper'/1448, l='MpServer', x=436.38, y=36.00, z=264.97], EntityCow['Cow'/297, l='MpServer', x=460.75, y=62.00, z=117.22], EntityCow['Cow'/298, l='MpServer', x=459.94, y=65.00, z=116.84], EntityCow['Cow'/299, l='MpServer', x=445.34, y=65.00, z=121.50], EntityCow['Cow'/300, l='MpServer', x=451.69, y=63.00, z=139.53], EntityCow['Cow'/301, l='MpServer', x=453.78, y=63.00, z=134.81], EntityCow['Cow'/304, l='MpServer', x=456.25, y=63.00, z=145.47], EntityCow['Cow'/311, l='MpServer', x=458.38, y=67.00, z=237.34], EntityBat['Bat'/2106, l='MpServer', x=371.25, y=30.10, z=176.25], EntityEnderman['Enderman'/2236, l='MpServer', x=430.50, y=32.00, z=106.50], EntityBat['Bat'/2111, l='MpServer', x=413.26, y=39.06, z=122.67], EntityCow['Cow'/320, l='MpServer', x=479.28, y=64.00, z=116.19], EntityItem['item.item.rottenFlesh'/1235, l='MpServer', x=453.28, y=64.00, z=201.50], EntityItem['item.item.rottenFlesh'/1239, l='MpServer', x=433.34, y=67.00, z=237.34], EntityBat['Bat'/2651, l='MpServer', x=438.33, y=36.82, z=105.79], EntityBat['Bat'/1372, l='MpServer', x=418.25, y=28.10, z=242.75], EntityVillager['Villager'/232, l='MpServer', x=368.28, y=93.00, z=120.69], EntityZombie['Zombie'/2541, l='MpServer', x=492.50, y=44.00, z=121.50], EntitySkeleton['Skeleton'/2542, l='MpServer', x=495.50, y=44.00, z=121.50], EntityFallingBlock['Falling Block'/371, l='MpServer', x=553.50, y=16.65, z=319.50], EntityFallingBlock['Falling Block'/372, l='MpServer', x=554.50, y=17.65, z=319.50], EntityFallingBlock['Falling Block'/373, l='MpServer', x=553.50, y=16.65, z=319.50], EntityXPOrb['Experience Orb'/2549, l='MpServer', x=433.68, y=62.00, z=181.63], EntityFallingBlock['Falling Block'/374, l='MpServer', x=554.50, y=17.94, z=319.50], EntityFallingBlock['Falling Block'/375, l='MpServer', x=553.50, y=16.94, z=319.50], EntityFallingBlock['Falling Block'/376, l='MpServer', x=554.50, y=17.94, z=319.50], EntityEnderman['Enderman'/1657, l='MpServer', x=369.50, y=33.00, z=223.50], EntityCow['Cow'/253, l='MpServer', x=392.13, y=70.00, z=221.81], EntityBat['Bat'/1533, l='MpServer', x=364.69, y=15.00, z=166.50], EntityCreeper['Creeper'/1790, l='MpServer', x=371.50, y=26.00, z=223.50], EntityCow['Cow'/255, l='MpServer', x=399.31, y=70.00, z=233.59]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.2 (latest: 2.2)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 194245864 bytes (185 MB) / 584777728 bytes (557 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Huahwi_Edited_Defscape.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by RaiderzFtw** [comment]
Sorry! I said the thing over again. xD

**Comment by GummiBoat** [comment]
# *Duplicate: #885*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

I know, it says it's fixed, but apparently it isn't. I think Alex will reopen the other Issue.

Also, there's a pencil right from your name at the top of your message, you can edit your Issue there.

**Comment by Alexander01998** [comment]
This one is slightly different from #885.
