### ISSUE TITLE
java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by WurstLeafeon** [Wurst-Imperium/Wurst-Client#194]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Oh - I know what I did wrong!

Time: 3/14/15 2:54 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.isRightButton(WurstButtonUI.java:206)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.renderComponent(WurstButtonUI.java:113)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.renderComponent(WurstButtonUI.java:30)
	at org.darkstorm.minecraft.gui.theme.AbstractComponentUI.render(AbstractComponentUI.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractComponent.render(AbstractComponent.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractContainer.render(AbstractContainer.java:28)
	at org.darkstorm.minecraft.gui.component.basic.BasicFrame.render(BasicFrame.java:35)
	at org.darkstorm.minecraft.gui.AbstractGuiManager.render(AbstractGuiManager.java:112)
	at org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen.drawScreen(GuiManagerDisplayScreen.java:119)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1204)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1376)
	at net.minecraft.client.Minecraft.run(Minecraft.java:464)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.isRightButton(WurstButtonUI.java:206)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.renderComponent(WurstButtonUI.java:113)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.renderComponent(WurstButtonUI.java:30)
	at org.darkstorm.minecraft.gui.theme.AbstractComponentUI.render(AbstractComponentUI.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractComponent.render(AbstractComponent.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractContainer.render(AbstractContainer.java:28)
	at org.darkstorm.minecraft.gui.component.basic.BasicFrame.render(BasicFrame.java:35)
	at org.darkstorm.minecraft.gui.AbstractGuiManager.render(AbstractGuiManager.java:112)
	at org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen.drawScreen(GuiManagerDisplayScreen.java:119)

-- Screen render details --
Details:
	Screen name: org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen
	Mouse location: Scaled: (363, 256). Absolute: (726, 255)
	Screen size: Scaled: (680, 384). Absolute: (1360, 768). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player'/350, l='MpServer', x=156.01, y=93.62, z=255.10]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 172.00,64.00,40.00 - World: (172,64,40), Chunk: (at 12,4,8 in 10,2; contains blocks 160,0,32 to 175,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 49619 game time, 49619 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityRabbit['Rabbit'/3334, l='MpServer', x=218.28, y=71.00, z=333.59], EntityPlayerSP['Player'/350, l='MpServer', x=156.01, y=93.62, z=255.10], EntityPig['Pig'/2948, l='MpServer', x=81.84, y=94.00, z=330.38], EntityChicken['Chicken'/156, l='MpServer', x=223.38, y=66.00, z=211.56], EntityCow['Cow'/1770, l='MpServer', x=152.72, y=94.00, z=287.44]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:3006)
	at net.minecraft.client.Minecraft.run(Minecraft.java:486)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.8 (latest: 1.8)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 161079440 bytes (153 MB) / 416112640 bytes (396 MB) up to 1559494656 bytes (1487 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1500M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8610G GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [LeafeonPVP]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
What where doing just before the crash?

**Comment by WurstLeafeon** [comment]
Keybinding my mods in singleplayer because the current keybind mechanic is terrible. I was switching between Wurst Settings and OpenGUI a lot, but other than that I have no idea what caused the crash.
