### ISSUE TITLE
Minecraft Wurst Client Crash Report On Windows 10.

### ISSUE THREAD

**Issue by DanielRobboSon** [Wurst-Imperium/Wurst-Client#1983]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 24/08/15 10:45 AM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.startLWJGL_3(Minecraft.java:618)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:444)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.startLWJGL_3(Minecraft.java:618)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:444)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: ~~ERROR~~ NullPointerException: null
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 25066352 bytes (23 MB) / 157528064 bytes (150 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
```

**Comment by DanielRobboSon** [comment]
This Happens Every Time I Press "Play" or "Play Offline"

**Comment by BoomBoomLHack** [comment]
Try to update your graphic card driver.

**Comment by Alexander01998** [comment]
This could either be caused by your graphics card or because you modified the `Wurst.jar` or `Wurst.json` file.

**Comment by PixelMaster3D** [comment]
When I downloaded wurst I used some random version for (version).json

**Comment by Alexander01998** [comment]
> When I downloaded wurst I used some random version for (version).json

That can cause a crash like this.

**Comment by Orcunegeacar** [comment]
Does Windows 10 support Geforce GT 220? Reply please

**Comment by PixelMaster3D** [comment]
But it dosen't. I've tried. It really works.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
