### ISSUE TITLE
it crashs when i open (Linux)

### ISSUE THREAD

**Issue by Daradous** [Wurst-Imperium/Wurst-Client#2079]
So just before you ask my java and everything is updated including my launcher, and yes other clients do work.

So what the problem is when i press play it crashes and wurst does not launch. 

Specs:
Operating system:Kali 2.0 amd64
Wurst version: 2.3.2

Crash output(game output):
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by jens1o** [comment]
Please use the Markdown... 
https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

(I mean the Game Output -> Code)

**Comment by BoomBoomLHack** [comment]
'''Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0'''
got java 8?

**Comment by PixelMaster3D** [comment]
This error means that the compiled code has relationship with JDK 8, but you are trying to run it on an earlier Java version, for example Java 7.That doesn't work; older versions of Java cannot run code compiled on newer versions of the JDK. Make sure you run the program with Java 8, or compile it with an older JDK version.

**Comment by PixelMaster3D** [comment]
version 52.0 is java 8.

**Comment by GlitchHead** [comment]
You need java 8 there are a few auto installers for linux.

**Comment by PixelMaster3D** [comment]
He has java 8. but it keeps referring to the old java version. So probably uninstall and re-install the java 8 . Or the problem is that java 8 has a java 7 compiled and you need to use a downgrade like java 7.

**Comment by GlitchHead** [comment]
@Daradous If you still cant manage to launch wurst check whats in the executable section of the launcher you might want to point that to java 8.

**Comment by PixelMaster3D** [comment]
Yeah that too. Thanks GlitchHead!

**Comment by Daradous** [comment]
Sorry guys that i haven't been repyling but thanks anyways i was so stupid that i didn't realise that my package updater didn't automatically update to Java 8, it wasn't even in the package manager so i just had to manually install it by adding the ubuntu oracle repo to my sources list then i apt-get update and then i had to add the keyserver to my keys server list then i apt-get installed oraclejavainstaller then installed java 8 from there and now it works, thanks for the feedback guys it really  helped and now it works :D
