### ISSUE TITLE
Crash when using X-Ray Manager

### ISSUE THREAD

**Issue by GhostGuy283** [Wurst-Imperium/Wurst-Client#2080]
I get this crash when i use x-ray manager

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Don't do that.

Time: 1-9-15 17:30
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tk.wurst_client.options.gui.GuiXRayBlocksManager.actionPerformed(GuiXRayBlocksManager.java:68)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiXRayBlocksManager.mouseClicked(GuiXRayBlocksManager.java:100)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tk.wurst_client.options.gui.GuiXRayBlocksManager.actionPerformed(GuiXRayBlocksManager.java:68)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiXRayBlocksManager.mouseClicked(GuiXRayBlocksManager.java:100)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: tk.wurst_client.options.gui.GuiXRayBlocksManager

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['GhostGuy283'/426, l='MpServer', x=661,49, y=5,00, z=456,89]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 588,00,73,00,269,00 - World: (588,73,269), Chunk: (at 12,4,13 in 36,16; contains blocks 576,0,256 to 591,255,271), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 65405301 game time, 65444681 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityOtherPlayerMP['powerjack'/199417, l='MpServer', x=574,67, y=64,00, z=397,69], EntityPig['Pig'/197131, l='MpServer', x=662,34, y=66,00, z=485,78], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=578,50, y=66,07, z=506,53], EntityOtherPlayerMP['MatthiasM'/199409, l='MpServer', x=553,16, y=64,00, z=490,72], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=562,81, y=106,00, z=502,18], EntityOtherPlayerMP['GhostGuy283'/-69, l='MpServer', x=562,82, y=66,00, z=467,30], EntityOtherPlayerMP['yepdude'/199736, l='MpServer', x=602,67, y=64,00, z=499,26], EntityOtherPlayerMP['VuurGeest72'/201677, l='MpServer', x=597,11, y=64,00, z=475,93], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=560,22, y=75,16, z=504,59], EntityChicken['Chicken'/190263, l='MpServer', x=638,03, y=55,00, z=438,03], EntityCreeper['Creeper'/197813, l='MpServer', x=635,53, y=46,00, z=477,03], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=578,74, y=105,00, z=504,05], EntityChicken['Chicken'/190266, l='MpServer', x=636,88, y=55,00, z=443,50], EntityChicken['Chicken'/190267, l='MpServer', x=639,56, y=55,00, z=439,34], EntityChicken['Chicken'/190264, l='MpServer', x=638,41, y=55,00, z=440,75], EntityChicken['Chicken'/190265, l='MpServer', x=639,25, y=55,00, z=446,44], EntityChicken['Chicken'/190270, l='MpServer', x=636,88, y=55,00, z=439,47], EntityChicken['Chicken'/190271, l='MpServer', x=641,25, y=55,00, z=445,50], EntityChicken['Chicken'/190268, l='MpServer', x=637,53, y=55,00, z=443,31], EntityChicken['Chicken'/190269, l='MpServer', x=637,81, y=55,00, z=446,53], EntityChicken['Chicken'/190274, l='MpServer', x=636,88, y=55,00, z=446,50], EntityChicken['Chicken'/190275, l='MpServer', x=636,91, y=55,00, z=441,84], EntityChicken['Chicken'/190272, l='MpServer', x=637,69, y=55,00, z=446,00], EntitySkeleton['Skeleton'/190273, l='MpServer', x=652,50, y=62,00, z=437,50], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=566,78, y=69,00, z=499,50], EntityOtherPlayerMP['VuurGeest72'/201677, l='MpServer', x=579,00, y=66,00, z=470,41], EntityZombie['Zombie'/192471, l='MpServer', x=663,44, y=34,00, z=473,09], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=575,18, y=106,00, z=499,20], EntityBat['Bat'/207709, l='MpServer', x=633,53, y=11,10, z=459,56], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=559,28, y=69,00, z=512,84], EntityOtherPlayerMP['MatthiasM'/199409, l='MpServer', x=600,25, y=65,03, z=450,97], EntityOtherPlayerMP['VuurGeest72'/201677, l='MpServer', x=606,28, y=63,00, z=470,28], EntityOtherPlayerMP['VuurGeest72'/201677, l='MpServer', x=587,31, y=64,00, z=447,03], EntityPlayerSP['GhostGuy283'/426, l='MpServer', x=661,49, y=5,00, z=456,89], EntityOtherPlayerMP['FUTbal'/189928, l='MpServer', x=574,06, y=102,00, z=501,75]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"93959ca":1065) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.3.2 (latest: unknown)
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264990104 bytes (252 MB) / 428339200 bytes (408 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7640G + 7670M Dual Graphics GL version 4.2.11774 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by PixelMaster3D** [comment]
The settings for the Xray failed due to some Mouse interaction with the blocks.
