### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by xXAwesomeXx** [Wurst-Imperium/Wurst-Client#2114]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// You're mean.

Time: 9/4/15 11:01 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderPainting.doRender(RenderPainting.java:40)
	at net.minecraft.client.renderer.entity.RenderPainting.doRender(RenderPainting.java:170)
	at net.minecraft.client.renderer.entity.RenderManager.doRenderEntity(RenderManager.java:381)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityWithPosYaw(RenderManager.java:361)
	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(TileEntityMobSpawnerRenderer.java:35)
	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_180539_a(TileEntityMobSpawnerRenderer.java:18)
	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.renderTileEntityAt(TileEntityMobSpawnerRenderer.java:41)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:148)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:128)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:681)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1401)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1134)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1298)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderPainting.doRender(RenderPainting.java:40)
	at net.minecraft.client.renderer.entity.RenderPainting.doRender(RenderPainting.java:170)

-- Entity being rendered --
Details:
	Entity Type: Painting (net.minecraft.entity.item.EntityPainting)
	Entity ID: 11309
	Entity Name: Painting
	Entity's Exact location: -56.00, 0.00, -33.00
	Entity's Block location: -56.00,0.00,-33.00 - World: (-56,0,-33), Chunk: (at 8,0,15 in -4,-3; contains blocks -64,0,-48 to -49,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPainting@5bdaeec8
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.8075471
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.doRenderEntity(RenderManager.java:381)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityWithPosYaw(RenderManager.java:361)
	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(TileEntityMobSpawnerRenderer.java:35)
	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_180539_a(TileEntityMobSpawnerRenderer.java:18)
	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.renderTileEntityAt(TileEntityMobSpawnerRenderer.java:41)

-- Block Entity Details --
Details:
	Name: MobSpawner // net.minecraft.tileentity.TileEntityMobSpawner
	Block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (307,57,282), Chunk: (at 3,3,10 in 19,17; contains blocks 304,0,272 to 319,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:148)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:128)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:681)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1401)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1315)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AwesomeHacker'/32883, l='MpServer', x=362.83, y=57.00, z=314.27]]
	Chunk stats: MultiplayerChunkCache: 442, 442
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 460.00,104.00,300.00 - World: (460,104,300), Chunk: (at 12,6,12 in 28,18; contains blocks 448,0,288 to 463,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1613124 game time, 288000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityPlayerSP['AwesomeHacker'/32883, l='MpServer', x=362.83, y=57.00, z=314.27], EntityOtherPlayerMP['xXxZexyZekxXx'/28698, l='MpServer', x=402.00, y=46.94, z=301.59], EntityOtherPlayerMP['CoreyMLG'/32905, l='MpServer', x=461.41, y=102.91, z=299.50], EntityOtherPlayerMP['iPods'/4748, l='MpServer', x=460.50, y=104.00, z=300.50], EntityOtherPlayerMP['HeroBrines_Child'/28665, l='MpServer', x=435.44, y=104.95, z=253.59]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b3d15d5":1078) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2925)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.3.2 (latest: 2.3.2)
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 147302192 bytes (140 MB) / 428449792 bytes (408 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce 9400M OpenGL Engine GL version 2.1 NVIDIA-10.0.35 310.90.10.05b12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Huahwi_Edited_Defscape]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by awakened-game** [comment]
looks like you have a painting in the game causing the crash, open the world in an editor such as NBTExplorer or MCEdt and remove the painting at -56 0 -33

**Comment by Garkolym3** [comment]
Yea, its normal in wurst, just reininstall it

**Comment by xXAwesomeXx** [comment]
ok, thanks

**Comment by PixelMaster3D** [comment]
It looks like a painting interacted with mobspawner. Is it possible that on the server that there was a painting on a mob spawner and then when it tried to spawn a mob, it overload because it couldn't spawn but it was saying it was.
