### ISSUE TITLE
Never loads anymore?!?!

### ISSUE THREAD

**Issue by scootaloo04** [Wurst-Imperium/Wurst-Client#2190]
I get this message whenever i try to load it I can normally load it fine, but the last few monthes its been like this: 
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by BoomBoomLHack** [comment]
Got Java 8?

**Comment by 1337HaxorKiddie** [comment]
Or IOS?

**Comment by awakened-game** [comment]
looks like your minecraft launcher is either out of date, or too new.
anyone confirm?

**Comment by Alexander01998** [comment]
See #1224 for information on how to fix this issue. (I added a TL;DR to make it easier to understand)

**Comment by scootaloo04** [comment]
I have a macbook pro... Version 10.8.6 is highest it goes

**Comment by PixelMaster3D** [comment]
Uninstall java and reinstall it if you want.

**Comment by mcccs** [comment]
@scootaloo04 do you see something like:
"posix_spawn doesn't work on this platform"

**Comment by scootaloo04** [comment]
@Alexander01998 This method does not work on my Macbook Pro. I need more help!

**Comment by mcccs** [comment]
@paris-ci 's method must work

**Comment by scootaloo04** [comment]
@mcccs Nope it dosnt .-. and @BoomBoomLHack I can't get java 8... My mac's version is too old.

**Comment by mcccs** [comment]
Are you sure?
Did you tried this method 
Select Wurst Profile
Tick executable
Paste this:
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java

**Comment by ex0rpass** [comment]
@mcccs I know how to do it!

Step one Throw out your mac

Step two Get a computer with the OS Windows

Step three load up wurst

step four TA DAAAAA

**Comment by mcccs** [comment]
No need to this, Just use BootCAmp

**Comment by PixelMaster3D** [comment]
@ex0rpass and @mcccs, you could Use Darik's Boot and Nuke (if you want a professional look).

https://www.youtube.com/watch?v=eZH1STQNAhY

**Comment by Alexander01998** [comment]
> I know how to do it!
> 
> Step one Throw out your mac
> 
> Step two Get a computer with the OS Windows
> 
> Step three load up wurst
> 
> step four TA DAAAAA

There, that works.
