### ISSUE TITLE
I keep crashing when I open the game

### ISSUE THREAD

**Issue by jekhi5** [Wurst-Imperium/Wurst-Client#2193]
Whenever I start to play I get the loading and then I crash. This is the message I get:

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

I am running yosemite on my apple macbook air.
Wurst version 1.9

**Comment by BoomBoomLHack** [comment]
1. Reinstall Wurst & get 2.0
2. Something's wrong with the altmanager
3. Got java 8?

**Comment by awakened-game** [comment]
- [x] Dont use a MAC

@Alexander01998 Tag: crApple

**Comment by Alexander01998** [comment]
See #1224 for information on how to fix this issue. (I added a TL;DR to make it easier to understand)
