### ISSUE TITLE
Crash...

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#2211]
```
[09:23:41] [Client thread/INFO]: Setting user: sidjaja
[09:23:41] [Client thread/INFO]: (Session ID is token:1337535510N:ca072ef8d00a31128daebd01d64a2915)
[09:23:43] [Client thread/INFO]: LWJGL Version: 2.9.1
[09:23:43] [Client thread/INFO]: Reloading ResourceManager: Default
[09:23:45] [Sound Library Loader/INFO]: Starting up SoundSystem...
[09:23:45] [Thread-8/INFO]: Initializing LWJGL OpenAL
[09:23:45] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
[09:23:46] [Thread-8/INFO]: OpenAL initialized.
[09:23:46] [Sound Library Loader/INFO]: Sound engine started
[09:23:49] [Client thread/INFO]: Created: 512x512 textures-atlas
javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(Unknown Source)
	at sun.security.rsa.RSAPadding.unpad(Unknown Source)
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at tk.wurst_client.alts.Encryption.loadKeys(Encryption.java:222)
	at tk.wurst_client.alts.Encryption.checkKeys(Encryption.java:93)
	at tk.wurst_client.alts.Encryption.decrypt(Encryption.java:73)
	at tk.wurst_client.files.FileManager.loadAlts(FileManager.java:425)
	at tk.wurst_client.files.FileManager.init(FileManager.java:95)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:61)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)
java.lang.NullPointerException
	at tk.wurst_client.alts.Encryption.decrypt(Encryption.java:78)
	at tk.wurst_client.files.FileManager.loadAlts(FileManager.java:425)
	at tk.wurst_client.files.FileManager.init(FileManager.java:95)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:61)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)
java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at tk.wurst_client.files.FileManager.loadAlts(FileManager.java:424)
	at tk.wurst_client.files.FileManager.init(FileManager.java:95)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:61)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)
[09:23:55] [Client thread/INFO]: No update found.
[09:24:05] [Client thread/WARN]: Unable to start LAN server detection: error setting options
[09:24:07] [Client thread/WARN]: Unable to start LAN server detection: error setting options
[09:24:08] [Client thread/INFO]: Connecting to play.voltrenz.net, 29065
[09:24:10] [Client thread/INFO]: [CHAT] [*] Session login
[09:24:10] [Client thread/INFO]: [CHAT] sidjaja has joined the server!
[09:24:11] [Client thread/INFO]: [CHAT] ?
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT] -+-----------------==========-----------------+-
[09:24:11] [Client thread/INFO]: [CHAT]             Welcome to the Voltrenz Network
[09:24:11] [Client thread/INFO]: [CHAT]                Player(s) online 2/100
[09:24:11] [Client thread/INFO]: [CHAT]                You join to the Lobby Network
[09:24:11] [Client thread/INFO]: [CHAT] 
[09:24:11] [Client thread/INFO]: [CHAT]              ? Type: /server to change server
[09:24:11] [Client thread/INFO]: [CHAT]              ? Important: Dont forget to vote xD
[09:24:11] [Client thread/INFO]: [CHAT]              ? Website: http://voltrenz.net
[09:24:11] [Client thread/INFO]: [CHAT]              ? Forum: http://voltrenz.net
[09:24:11] [Client thread/INFO]: [CHAT]              ? Teamspeak: teamspeak.voltrenz.net:6325
[09:24:11] [Client thread/INFO]: [CHAT] You have no new mail.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa93b6cfc3, pid=1868, tid=792
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x6cfc3]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Billy\AppData\Roaming\.minecraft\hs_err_pid1868.log
Compiled method (c1)   80367 6028       2       net.minecraft.client.renderer.OpenGlHelper::func_176072_g (20 bytes)
 total in heap  [0x00000000031e4710,0x00000000031e50c8] = 2488
 relocation     [0x00000000031e4830,0x00000000031e48c8] = 152
 main code      [0x00000000031e48e0,0x00000000031e4c00] = 800
 stub code      [0x00000000031e4c00,0x00000000031e4cf8] = 248
 oops           [0x00000000031e4cf8,0x00000000031e4d00] = 8
 metadata       [0x00000000031e4d00,0x00000000031e4d38] = 56
 scopes data    [0x00000000031e4d38,0x00000000031e4f90] = 600
 scopes pcs     [0x00000000031e4f90,0x00000000031e50a0] = 272
 dependencies   [0x00000000031e50a0,0x00000000031e50a8] = 8
 nul chk table  [0x00000000031e50a8,0x00000000031e50c8] = 32
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```

**Comment by mcccs** [comment]
@billyoz you can't share your session id! someone can login as you!

**Comment by awakened-game** [comment]
@mcccs ummm, the session ID clearly says 1337535510N
do you not understand l3375P33k?

**Comment by billyoz** [comment]
yes i dont understand

**Comment by awakened-game** [comment]
@billyoz not you, i was talking to @mcccs 

as for the crash, looks like you need to delete your keys and start again, @Alexander01998 has a guide on that somewhere.

**Comment by billyoz** [comment]
how to delete?

**Comment by awakened-game** [comment]
look for the guide by @Alexander01998

**Comment by billyoz** [comment]
where is the guide?

**Comment by Alexander01998** [comment]
#570

**Comment by Orcunegeacar** [comment]
It's ok. This ID is not correct. He is using cracked account.

**Comment by awakened-game** [comment]
@Orcunegeacar already mentioned that, its quite obvious
