### ISSUE TITLE
Crash - 9/15/15

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#2236]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why is it breaking :(

Time: 9/15/15 10:00 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.gui.GuiGameOver.confirmClicked(GuiGameOver.java:85)
	at net.minecraft.client.gui.GuiYesNo.actionPerformed(GuiYesNo.java:64)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.GuiGameOver.confirmClicked(GuiGameOver.java:85)
	at net.minecraft.client.gui.GuiYesNo.actionPerformed(GuiYesNo.java:64)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:383)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.4 (latest: unknown)
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 130608800 bytes (124 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel 965/963 Graphics Media Accelerator GL version 2.0.0 - Build 8.14.10.1930, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by PixelMaster3D** [comment]
I know what the problem is but hope you would figure it out.

**Comment by ex0rpass** [comment]
@PixelMaster3D Sorry this is not on topic but can i add you on steam? we can grief togeter and i know some unprotected servers

**Comment by PixelMaster3D** [comment]
I don't have a steam account but i will make one and tell you. @Alexander01998 the problem was that my computer couldn't load as fast as it was and it crashed because of 2.3 GHz CPU that couldn't process. It wouldn't crash browser so i crashed it myself using task manager. That's the problem. Now we need a resolution. We need to make Wurst process slowly.

**Comment by Alexander01998** [comment]
From the crash log, it looks like there was a problem with AutoRespawn or the respawn screen.
Slow CPUs usually can't cause crashes.

**Comment by PixelMaster3D** [comment]
Yes, that was the also the reason. We can tell when we see net.minecraft.client.gui.GuiGameOver and compare this to net.minecraft.client.gui.GuiMainMenu and :boom: we get Respawn. But besides the point. It was a lagging computer that had a x32 bit on a x64 bit system.
