### ISSUE TITLE
Run Out Of Memory 

### ISSUE THREAD

**Issue by HeyImFanta** [Wurst-Imperium/Wurst-Client#2252]
I have checked for similair issues.

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why is it breaking :(

Time: 24-09-15 18:24
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at net.minecraft.client.renderer.texture.TextureUtil.func_177055_a(TextureUtil.java:369)
	at net.minecraft.client.renderer.texture.TextureMap.loadTextureAtlas(TextureMap.java:278)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83)
	at net.minecraft.client.resources.model.ModelBakery.func_177572_j(ModelBakery.java:666)
	at net.minecraft.client.resources.model.ModelBakery.setupModelRegistry(ModelBakery.java:87)
	at net.minecraft.client.resources.model.ModelManager.onResourceManagerReload(ModelManager.java:26)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:514)
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at net.minecraft.client.renderer.texture.TextureUtil.func_177055_a(TextureUtil.java:369)
	at net.minecraft.client.renderer.texture.TextureMap.loadTextureAtlas(TextureMap.java:278)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83)
	at net.minecraft.client.resources.model.ModelBakery.func_177572_j(ModelBakery.java:666)
	at net.minecraft.client.resources.model.ModelBakery.setupModelRegistry(ModelBakery.java:87)
	at net.minecraft.client.resources.model.ModelManager.onResourceManagerReload(ModelManager.java:26)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:514)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:363)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: ~~ERROR~~ NullPointerException: null
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 327664896 bytes (312 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.6.33, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [§4Ign§8ite]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
Well, then you either don't have enough RAM to run it or you didn't allocate enough of that RAM to Minecraft. The latter is more likely, as you do have a 64 bit system.

There are plenty of tutorials out there on how to allocate more RAM to Minecraft.
Playing without your Resource Pack ("Ignite") could help as well, as Resource Packs usually eat up a lot of RAM.
