### ISSUE TITLE
Wurst updater - Error report: Connection reset

### ISSUE THREAD

**Issue by Kingtheempire** [Wurst-Imperium/Wurst-Client#2293]
# Description
Auto-generated error report.

# Stacktrace
```
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.MeteredStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at tk.wurst_client.updater.Main.download(Main.java:194)
	at tk.wurst_client.updater.Main.access$2(Main.java:179)
	at tk.wurst_client.updater.Main$1.run(Main.java:84)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by BoomBoomLHack** [comment]
check your internet?

**Comment by PixelMaster3D** [comment]
Your internet couldn't connect to this domain and failed to download the reqs. Just download it here manually if it ever breaks again.
