### ISSUE TITLE
crash on starting the client

### ISSUE THREAD

**Issue by tykodey** [Wurst-Imperium/Wurst-Client#2300]
please help me with that!          

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by tykodey** [comment]
ohhhhh i need to use the new launcher?

**Comment by mcccs** [comment]
#1224

**Comment by Alexander01998** [comment]
> ohhhhh i need to use the new launcher?

Yeah. Make sure you get the .jar version, not the .dmg one.
