### ISSUE TITLE
Arithmetic crash

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#2313]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// My bad.

Time: 11.10.2015 09:47
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at tk.wurst_client.gui.GuiWurstMainMenu.drawScreen(GuiWurstMainMenu.java:327)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1180)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1297)
	at net.minecraft.client.Minecraft.run(Minecraft.java:382)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.gui.GuiWurstMainMenu.drawScreen(GuiWurstMainMenu.java:327)

-- Screen render details --
Details:
	Screen name: tk.wurst_client.gui.GuiWurstMainMenu
	Mouse location: Scaled: (310, 239). Absolute: (621, 0)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1180)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1297)
	at net.minecraft.client.Minecraft.run(Minecraft.java:382)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.6 (latest: 2.6)
	Operating System: Mac OS X (x86_64) version 10.11
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 470084392 bytes (448 MB) / 1070596096 bytes (1021 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 1 total; -Xmx16G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: AMD Radeon R9 M370X OpenGL Engine GL version 2.1 ATI-1.36.46, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [§eColora!, §lDefault 3D§r Heavy     §lV5]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by mcccs** [comment]
Duplicate: #2307
