### ISSUE TITLE
Importing Alts is Crashing Client

### ISSUE THREAD

**Issue by NotKnee** [Wurst-Imperium/Wurst-Client#365]
I was importing a list of several hundred alts when this error was thrown. The alts list was a .txt file so I don't think that is the problem. Also, I'm fairly sure that when it was importing the alts it started showing that it had imported more alts than were in the list. 

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/29/15 9:43 PM
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index: 518, Size: 289
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tk.wurst_client.gui.alts.GuiAltList.drawSlot(GuiAltList.java:111)
	at tk.wurst_client.gui.GuiWurstSlot.func_148120_b(GuiWurstSlot.java:465)
	at tk.wurst_client.gui.GuiWurstSlot.drawScreen(GuiWurstSlot.java:328)
	at tk.wurst_client.gui.alts.GuiAlts.drawScreen(GuiAlts.java:256)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1206)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1380)
	at net.minecraft.client.Minecraft.run(Minecraft.java:468)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tk.wurst_client.gui.alts.GuiAltList.drawSlot(GuiAltList.java:111)
	at tk.wurst_client.gui.GuiWurstSlot.func_148120_b(GuiWurstSlot.java:465)
	at tk.wurst_client.gui.GuiWurstSlot.drawScreen(GuiWurstSlot.java:328)
	at tk.wurst_client.gui.alts.GuiAlts.drawScreen(GuiAlts.java:256)

-- Screen render details --
Details:
	Screen name: tk.wurst_client.gui.alts.GuiAlts
	Mouse location: Scaled: (456, 318). Absolute: (913, 163)
	Screen size: Scaled: (640, 400). Absolute: (1280, 800). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1206)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1380)
	at net.minecraft.client.Minecraft.run(Minecraft.java:468)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.10 (latest: 1.10)
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 142015104 bytes (135 MB) / 300265472 bytes (286 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.2.46, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
Any idea how to reproduce this? Importing alt lists is working fine for me.

**Comment by pokeball99** [comment]
try this @Alexander01998 http://www.google.com/#safe=active&q=minecraft+accounts+site:pastebin.com

**Comment by Alexander01998** [comment]
> try this @Alexander01998 http://www.google.com/#safe=active&q=minecraft+accounts+site:pastebin.com

I have plenty of alts to test, but they are all importing properly.

**Comment by pokeball99** [comment]
well he said it was a large amount,so maybe it was a overflow error?

**Comment by Alexander01998** [comment]
You can see in the stacktrace that it's an `IndexOutOfBoundsException`, not a `StackOverflowError`.

**Comment by Nitrogen-Dioxide** [comment]
Go to your wurst folder in .minecraft , and delete the " key " file, and " alts.json" **Be careful, deleting this files, deletes all your alts too!** . Idk if it will fix but, worked for me...

**Comment by NotKnee** [comment]
Sorry, I may not have been very clear. This is what I did that made it happen: 1) I downloaded and ran the Wurst client for the first time, 2) I then loaded a list of ~150 alts onto it and it seemed to work just fine, 3) I tried loading more alts and it would only do about half of them, stop and then save, 4) I tried loading a large list of alts and it just crashed after the alts count went WAY above the amount of alts I was loading (I was loading around 400 and it was counting past 500).

**Comment by Alexander01998** [comment]
The same bug has now been reported on Windows. Issue #855 will be used from now on.
