### ISSUE TITLE
An error occurred in `PlayerFinder` while receiving packet.

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#398]
# Description
An error occurred in `PlayerFinder` while receiving packet.
S29PacketSoundEffect

# Server
us.mineplex.com
# Stacktrace
```
java.lang.NullPointerException
	at tk.wurst_client.utils.BlockUtils.getPlayerBlockDistance(BlockUtils.java:93)
	at tk.wurst_client.utils.BlockUtils.getPlayerBlockDistance(BlockUtils.java:86)
	at tk.wurst_client.mod.mods.PlayerFinder.onReceivedPacket(PlayerFinder.java:88)
	at tk.wurst_client.event.EventManager$6.listen(EventManager.java:102)
	at tk.wurst_client.event.EventManager$6.listen(EventManager.java:97)
	at tk.wurst_client.event.EventManager.fireEvent(EventManager.java:159)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:450)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handle

**Comment by WurstLeafeon** [comment]
[SINGLE PLAYER]

# Description
An error occurred in `PlayerFinder` while receiving packet.
S29PacketSoundEffect

# Stacktrace
```
java.lang.NullPointerException
	at tk.wurst_client.utils.BlockUtils.getPlayerBlockDistance(BlockUtils.java:93)
	at tk.wurst_client.utils.BlockUtils.getPlayerBlockDistance(BlockUtils.java:86)
	at tk.wurst_client.mod.mods.PlayerFinder.onReceivedPacket(PlayerFinder.java:88)
	at tk.wurst_client.event.EventManager$6.listen(EventManager.java:102)
	at tk.wurst_client.event.EventManager$6.listen(EventManager.java:97)
	at tk.wurst_client.event.EventManager.fireEvent(EventManager.java:159)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:450)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:312)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:44)
	at io.netty.channel.local.LocalChannel$6.run(LocalChannel.java:298)
	at io.netty.channel.local.LocalEventLoop.run(LocalEventLoop.java:33)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)
```

# System details
- OS: Windows 8.1 (amd64)
- Java version: 1.8.0_25 (Oracle Corporation)
- Wurst version: 1.11.1 (latest: 1.11.1)
