### ISSUE TITLE
Crashed apon launch.

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#617]
Crashed when was starting up
Crash report
```
---- Please report this crash at: wurst-client.tk/bugs ----
// Surprise! Haha. Well, this is awkward.

Time: 4/24/15 8:45 PM
Description: Rendering screen

java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at net.minecraft.client.gui.GuiMainMenu.drawScreen(GuiMainMenu.java:699)
at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1198)
at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
at net.minecraft.client.Minecraft.run(Minecraft.java:411)
at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at net.minecraft.client.gui.GuiMainMenu.drawScreen(GuiMainMenu.java:699)

-- Screen render details --
Details:
Screen name: net.minecraft.client.gui.GuiMainMenu
Mouse location: Scaled: (0, 352). Absolute: (0, 0)
Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2
Stacktrace:
at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1198)
at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
at net.minecraft.client.Minecraft.run(Minecraft.java:411)
at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
Minecraft Version: 1.8
Wurst Client Version: 1.14 (latest: 1.14)
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 112912440 bytes (107 MB) / 319361024 bytes (304 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: Wurst
LWJGL: 2.9.1
OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3412, Intel
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: [faithful32pack 1.8, Music]
Current Language: English (US)
Profiler Position: N/A (disabled)
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Brandon\AppData\Roaming.minecraft\crash-reports\crash-2015-04-24_20.45.00-client.txt
```

**Comment by Alexander01998** [comment]
When including error output, please wrap it into a [Markdown code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) so that it renders nicely.
Example:

<pre>```
java.lang.NullPointerException: null
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
```</pre>

**Comment by failvenom** [comment]
Sorry but i dont spend alot of time on GitHub so idk how to do that

**Comment by failvenom** [comment]
ok?
