### ISSUE TITLE
Exception in thread "Client thread" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#629]
I get this when running wurst in eclipse

Completely ignored arguments: [Add, these:]
Exception in thread "Client thread" java.lang.ExceptionInInitializerError
	at net.minecraft.util.StatCollector.<clinit>(StatCollector.java:5)
	at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:293)
	at net.minecraft.item.Item.getItemStackDisplayName(Item.java:416)
	at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:590)
	at net.minecraft.item.ItemStack.getChatComponent(ItemStack.java:1031)
	at net.minecraft.stats.StatList.func_151181_c(StatList.java:184)
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:112)
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:560)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:380)
	at net.minecraft.client.main.Main.main(Main.java:114)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
	at net.minecraft.util.StringTranslate.<init>(StringTranslate.java:42)
	at net.minecraft.util.StringTranslate.<clinit>(StringTranslate.java:28)
	... 10 more

**Comment by Alexander01998** [comment]
This error is caused by your edits, so you need to fix it on your own.

Looks to me like you are missing some assets, unless `Add, these:` are your actual parameters.

**Comment by scriptinator** [comment]
Oh lol

**Comment by scriptinator** [comment]
How is it disconfirmed?

**Comment by OMGchangeMYusername** [comment]
@scriptinator this is not an error that everyone get,it's just caused by your edits,that's why.

**Comment by scriptinator** [comment]
I did not edit it

**Comment by OMGchangeMYusername** [comment]
Well.. how can he reproduce it? if he couldn't,then it is disconfirmed.

**Comment by Alexander01998** [comment]
> and I just have my FML args.

---
> I did not edit it

You said that you added FML to it. That is editing. That's a lot of editing actually.

**Comment by scriptinator** [comment]
I added program arguments for Minecraft like --userToken and stuff other than that I pulled it off of Github those launch args are also used by FML

**Comment by Alexander01998** [comment]
Have you tried it without those arguments?

**Comment by scriptinator** [comment]
Yes and it gives an argument error

**Comment by scriptinator** [comment]
The argument error in which you need to add launch args.

**Comment by scriptinator** [comment]
The correct way to fix this is to drag the assets folder from the official 1.8 jar. Drag it on to Wurst-Client/Wurst-Client/src

**Comment by Alexander01998** [comment]
> The correct way to fix this is to drag the assets folder from the official 1.8 jar. Drag it on to Wurst-Client/Wurst-Client/src

Actually, you need to add the original 1.8.jar as a library, which you always need to do when developing a Minecraft mod.

**Comment by scriptinator** [comment]
You should add that to the debugging wurst in eclipse page on the wiki because the only modding I have done was the easy forge step by step tutorials
