### ISSUE TITLE
WSpam Crash

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#633]
I typed this script
```html
<repeat 90>
.tp ~-1 ~ ~1
.jump
.tp ~1 ~ ~-1
</repeat>
```
in singleplayer with 50 ms delay. And minecraft said "Not Responding"
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Don't be sad, have a hug! <3

Time: 26.04.2015 15:53
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Notch_s_hero'/252790, l='MpServer', x=75,00, y=4,00, z=1406,00]]
	Chunk stats: MultiplayerChunkCache: 439, 439
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 77,00,4,00,1434,00 - World: (77,4,1434), Chunk: (at 13,0,10 in 4,89; contains blocks 64,0,1424 to 79,255,1439), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 23413 game time, 23413 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 82 total; [EntityCreeper['Creeper'/446215, l='MpServer', x=136,50, y=4,00, z=1400,50], EntityZombie['Zombie'/319759, l='MpServer', x=103,13, y=4,00, z=1385,59], EntityCow['Cow'/252695, l='MpServer', x=141,31, y=4,00, z=1419,84], EntityRabbit['Rabbit'/252694, l='MpServer', x=143,09, y=4,00, z=1407,59], EntityHorse['Horse'/252696, l='MpServer', x=137,19, y=4,00, z=1411,66], EntityBat['Bat'/413720, l='MpServer', x=89,49, y=5,06, z=1464,63], EntitySlime['Slime'/574998, l='MpServer', x=46,34, y=4,02, z=1411,41], EntitySkeleton['Skeleton'/319771, l='MpServer', x=126,88, y=4,00, z=1384,34], EntitySkeleton['Skeleton'/433191, l='MpServer', x=99,19, y=4,00, z=1484,25], EntityHorse['Horse'/252719, l='MpServer', x=145,09, y=4,00, z=1360,75], EntityHorse['Horse'/252723, l='MpServer', x=145,06, y=4,00, z=1399,91], EntityHorse['Horse'/252722, l='MpServer', x=145,59, y=4,00, z=1362,53], EntityCow['Cow'/252721, l='MpServer', x=150,59, y=4,00, z=1367,03], EntitySlime['Slime'/477237, l='MpServer', x=124,38, y=5,07, z=1454,89], EntityHorse['Horse'/252720, l='MpServer', x=147,34, y=4,00, z=1362,50], EntityHorse['Horse'/252727, l='MpServer', x=144,72, y=4,00, z=1421,28], EntityCow['Cow'/252726, l='MpServer', x=146,50, y=4,00, z=1421,75], EntityCow['Cow'/252725, l='MpServer', x=142,81, y=4,00, z=1402,19], EntityCow['Cow'/252728, l='MpServer', x=152,06, y=4,00, z=1418,25], EntitySpider['Spider'/446269, l='MpServer', x=47,50, y=4,00, z=1481,50], EntityItem['item.item.egg'/413763, l='MpServer', x=62,81, y=4,00, z=1457,41], EntitySlime['Slime'/477248, l='MpServer', x=122,30, y=4,70, z=1455,31], EntitySlime['Slime'/456522, l='MpServer', x=134,06, y=4,02, z=1386,72], EntityBat['Bat'/385110, l='MpServer', x=94,25, y=6,71, z=1437,45], EntityZombie['Zombie'/394325, l='MpServer', x=67,50, y=4,00, z=1472,50], EntitySlime['Slime'/545115, l='MpServer', x=136,03, y=4,00, z=1334,00], EntityCreeper['Creeper'/413791, l='MpServer', x=27,50, y=4,00, z=1427,50], EntitySlime['Slime'/459354, l='MpServer', x=43,34, y=4,00, z=1391,13], EntitySpider['Spider'/433251, l='MpServer', x=100,50, y=4,00, z=1379,50], EntityBat['Bat'/366453, l='MpServer', x=68,58, y=9,27, z=1439,59], EntityItem['item.item.egg'/304244, l='MpServer', x=29,69, y=4,00, z=1432,25], EntityPlayerSP['Notch_s_hero'/252790, l='MpServer', x=75,00, y=4,00, z=1406,00], EntityBat['Bat'/366448, l='MpServer', x=76,75, y=11,06, z=1388,04], EntityCow['Cow'/252547, l='MpServer', x=7,28, y=4,00, z=1342,25], EntityChicken['Chicken'/252551, l='MpServer', x=7,69, y=4,00, z=1398,44], EntityCow['Cow'/252550, l='MpServer', x=5,16, y=4,00, z=1362,19], EntityCow['Cow'/252549, l='MpServer', x=6,34, y=4,00, z=1351,69], EntityCow['Cow'/252548, l='MpServer', x=6,66, y=4,00, z=1352,94], EntitySlime['Slime'/553856, l='MpServer', x=11,44, y=4,91, z=1482,54], EntityBat['Bat'/271755, l='MpServer', x=148,16, y=4,19, z=1461,63], EntitySkeleton['Skeleton'/413846, l='MpServer', x=67,94, y=4,00, z=1392,22], EntitySkeleton['Skeleton'/413847, l='MpServer', x=71,72, y=4,00, z=1369,72], EntitySkeleton['Skeleton'/413842, l='MpServer', x=144,50, y=4,00, z=1458,50], EntitySkeleton['Skeleton'/413840, l='MpServer', x=136,81, y=4,00, z=1460,75], EntityWitch['Witch'/433308, l='MpServer', x=13,50, y=4,00, z=1476,50], EntityWitch['Witch'/433309, l='MpServer', x=9,75, y=4,00, z=1481,31], EntityChicken['Chicken'/252575, l='MpServer', x=29,28, y=4,00, z=1432,53], EntityChicken['Chicken'/252574, l='MpServer', x=21,59, y=4,00, z=1435,34], EntityChicken['Chicken'/252572, l='MpServer', x=9,66, y=4,00, z=1409,53], EntityCow['Cow'/252579, l='MpServer', x=38,00, y=4,00, z=1481,03], EntityCow['Cow'/252578, l='MpServer', x=21,84, y=4,00, z=1480,47], EntitySheep['Sheep'/252587, l='MpServer', x=47,56, y=4,00, z=1348,16], EntityRabbit['Rabbit'/252591, l='MpServer', x=33,53, y=4,00, z=1401,47], EntityRabbit['Rabbit'/252590, l='MpServer', x=38,00, y=4,00, z=1395,41], EntityBat['Bat'/405675, l='MpServer', x=87,79, y=5,05, z=1438,51], EntitySheep['Sheep'/252589, l='MpServer', x=35,59, y=4,00, z=1348,75], EntitySheep['Sheep'/252588, l='MpServer', x=39,06, y=4,00, z=1353,00], EntitySpider['Spider'/252595, l='MpServer', x=40,97, y=4,00, z=1413,97], EntityRabbit['Rabbit'/252593, l='MpServer', x=38,59, y=4,00, z=1400,91], EntityRabbit['Rabbit'/252592, l='MpServer', x=52,17, y=4,19, z=1404,79], EntitySkeleton['Skeleton'/433095, l='MpServer', x=8,19, y=4,00, z=1377,66], EntitySkeleton['Skeleton'/446146, l='MpServer', x=45,72, y=4,00, z=1472,78], EntitySheep['Sheep'/252614, l='MpServer', x=48,84, y=4,00, z=1342,06], EntityChicken['Chicken'/252618, l='MpServer', x=56,56, y=4,00, z=1469,59], EntitySheep['Sheep'/252617, l='MpServer', x=55,72, y=4,00, z=1465,31], EntityChicken['Chicken'/252616, l='MpServer', x=63,31, y=4,00, z=1456,59], EntitySkeleton['Skeleton'/433099, l='MpServer', x=3,78, y=4,00, z=1373,72], EntitySlime['Slime'/535512, l='MpServer', x=11,16, y=4,00, z=1396,75], EntityBat['Bat'/386775, l='MpServer', x=123,34, y=4,50, z=1440,69], EntityBat['Bat'/445918, l='MpServer', x=140,47, y=7,02, z=1480,96], EntityCreeper['Creeper'/446179, l='MpServer', x=19,66, y=4,00, z=1483,22], EntityCreeper['Creeper'/446177, l='MpServer', x=17,69, y=4,00, z=1483,53], EntitySpider['Spider'/446189, l='MpServer', x=155,50, y=4,00, z=1426,50], EntitySlime['Slime'/474600, l='MpServer', x=50,91, y=4,02, z=1376,94], EntitySlime['Slime'/576999, l='MpServer', x=30,56, y=4,70, z=1480,79], EntityBat['Bat'/380404, l='MpServer', x=77,19, y=12,03, z=1399,28], EntitySkeleton['Skeleton'/252663, l='MpServer', x=128,91, y=4,02, z=1416,56], EntitySlime['Slime'/584688, l='MpServer', x=133,70, y=5,07, z=1339,88], EntitySkeleton['Skeleton'/252664, l='MpServer', x=102,31, y=4,00, z=1397,78], EntityCreeper['Creeper'/385273, l='MpServer', x=50,50, y=4,00, z=1383,50], EntityBat['Bat'/283386, l='MpServer', x=121,70, y=4,28, z=1452,61], EntityCreeper['Creeper'/394232, l='MpServer', x=105,50, y=4,00, z=1485,50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 128607584 bytes (122 MB) / 353869824 bytes (337 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7400M Series GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Nitrogen-Dioxide** [comment]
wait, did it crashed because the ~ ?

**Comment by GummiBoat** [comment]
Nope. It didn't crashed as I tested that either. I can't see the point of your Script, but for me it's working fine.

**Comment by Nitrogen-Dioxide** [comment]
@mcccs I think that you used too much ram or processor for that... 50ms is 20 times per second!

**Comment by OMGchangeMYusername** [comment]
lol it's also working fine here :+1: 
but what is the point as gummi said?

**Comment by OMGchangeMYusername** [comment]
it spams the chat with: 
username: (nothing O_o)
[Wurst] [ERROR] can't jump in mid-air
and on

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername 
Well... it looks like a phase hack trough wspam haha

**Comment by GummiBoat** [comment]
The username: nothing is because he did something wrong with the repeat. if you want to avoid that you have to type 
<repeat x>first line
second line
</repeat>

Yeah, @Nitrogen-Dioxide is right, it seems way too much for his computer to handle and he broke while rendering the chat.

And ... even for a phase this seems pretty.. you know.. crazy?

**Comment by Alexander01998** [comment]
Actually, this is how to repeat a full chat message/command:

```HTML
.nothing<repeat 123>
§message;</repeat>
```

The trick is making sure that none of the code will compile into empty lines.

**Comment by Alexander01998** [comment]
This bug actually had nothing to do with WSPAM. It was an EventManager thing that was fixed quite a while ago.
