### ISSUE TITLE
GUI Crash

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#640]
Whenever I open the gui, I crash. I haven't changed anything so I don't know what's causing it. Here's the log.

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I let you down. Sorry :(

Time: 4/26/15 7:03 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: -1
	at org.darkstorm.minecraft.gui.component.basic.BasicComboBox.getSelectedElement(BasicComboBox.java:65)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstComboBoxUI.renderComponent(WurstComboBoxUI.java:224)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstComboBoxUI.renderComponent(WurstComboBoxUI.java:23)
	at org.darkstorm.minecraft.gui.theme.AbstractComponentUI.render(AbstractComponentUI.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractComponent.render(AbstractComponent.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractContainer.render(AbstractContainer.java:28)
	at org.darkstorm.minecraft.gui.component.basic.BasicFrame.render(BasicFrame.java:35)
	at org.darkstorm.minecraft.gui.AbstractGuiManager.render(AbstractGuiManager.java:112)
	at org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen.drawScreen(GuiManagerDisplayScreen.java:119)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1198)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.darkstorm.minecraft.gui.component.basic.BasicComboBox.getSelectedElement(BasicComboBox.java:65)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstComboBoxUI.renderComponent(WurstComboBoxUI.java:224)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstComboBoxUI.renderComponent(WurstComboBoxUI.java:23)
	at org.darkstorm.minecraft.gui.theme.AbstractComponentUI.render(AbstractComponentUI.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractComponent.render(AbstractComponent.java:32)
	at org.darkstorm.minecraft.gui.component.AbstractContainer.render(AbstractContainer.java:28)
	at org.darkstorm.minecraft.gui.component.basic.BasicFrame.render(BasicFrame.java:35)
	at org.darkstorm.minecraft.gui.AbstractGuiManager.render(AbstractGuiManager.java:112)
	at org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen.drawScreen(GuiManagerDisplayScreen.java:119)

-- Screen render details --
Details:
	Screen name: org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen
	Mouse location: Scaled: (320, 179). Absolute: (960, 540)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Eveythingistaken'/3672258, l='MpServer', x=-629.82, y=151.00, z=-206.44]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -416.00,153.00,1258.00 - World: (-416,153,1258), Chunk: (at 0,9,10 in -26,78; contains blocks -416,0,1248 to -401,255,1263), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Level time: 6368941 game time, 6368941 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 13 total; [EntityPlayerSP['Eveythingistaken'/3672258, l='MpServer', x=-629.82, y=151.00, z=-206.44], EntityCow['Cow'/3673512, l='MpServer', x=-647.94, y=151.00, z=-210.94], EntityCow['Cow'/3673513, l='MpServer', x=-647.94, y=151.00, z=-208.44], EntityItem['item.tile.cloth.silver'/3673514, l='MpServer', x=-645.16, y=151.00, z=-209.13], EntityXPOrb['Experience Orb'/3673515, l='MpServer', x=-648.03, y=151.00, z=-210.41], EntitySheep['Sheep'/3673516, l='MpServer', x=-646.50, y=151.00, z=-210.03], EntitySheep['Sheep'/3673504, l='MpServer', x=-643.09, y=151.00, z=-207.25], EntitySheep['Sheep'/3673505, l='MpServer', x=-646.56, y=151.00, z=-206.75], EntityCow['Cow'/3673511, l='MpServer', x=-647.94, y=151.00, z=-209.69], EntityCow['Cow'/3673500, l='MpServer', x=-643.09, y=151.00, z=-206.09], EntityCow['Cow'/3673501, l='MpServer', x=-647.94, y=151.00, z=-206.09], EntitySheep['Sheep'/3673502, l='MpServer', x=-643.94, y=151.00, z=-208.91], EntityCow['Cow'/3673503, l='MpServer', x=-647.94, y=151.00, z=-207.28]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"fa828eb":1059) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:433)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14)
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1422368176 bytes (1356 MB) / 2091384832 bytes (1994 MB) up to 2091384832 bytes (1994 MB)
	JVM Flags: 2 total; -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 640M OpenGL Engine GL version 2.1 NVIDIA-10.2.7 310.41.25f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by eveythingistaken** [comment]
Wow, thanks guys >.<

**Comment by TekkitCommando** [comment]
I honestly don't know what to tell you here, something about an entity (cow) and you, I can't be sure if it's the server or the client, I wanna say client... maybe

**Comment by TekkitCommando** [comment]
There was also a sheep involved xD

**Comment by GummiBoat** [comment]
@TekkitCommando Wow.. you're like.. completeley wrong. The GUI that's generating when he opens it, is "OutOfBound".

@eveythingistaken Please try resizing your MineCraft-GUI before you open a world. You can do that by going to Options -> Video Settings -> GUI-Scale. Try out "Small" at first and then increase it slowly while opening the GUI in-game and closing it again.

**Comment by Alexander01998** [comment]
When including error output, please wrap it into a [Markdown code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) so that it renders nicely.
Example:

<pre>```
java.lang.NullPointerException: null
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
```</pre>

**Comment by TekkitCommando** [comment]
Yep I knew I was wrong I was doing that too joke around lol :P

**Comment by eveythingistaken** [comment]
Thanks guys but I figured it out. I just deleted my gui file. But then I logged back on to that server, and i opened autobiild and it crashed again. So now I'm just leaving the autobiild tab closed.

**Comment by eveythingistaken** [comment]
Autobuild*
