### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#645]
Using debug mode I see that some classes return null even though I never modified them. I get this when I launch as an error and then the program crash:

Exception in thread "Client thread" java.lang.ExceptionInInitializerError
at net.minecraft.util.StatCollector.(StatCollector.java:5)
at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:293)
at net.minecraft.item.Item.getItemStackDisplayName(Item.java:416)
at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:590)
at net.minecraft.item.ItemStack.getChatComponent(ItemStack.java:1031)
at net.minecraft.stats.StatList.func_151181_c(StatList.java:184)
at net.minecraft.stats.StatList.func_151178_a(StatList.java:112)
at net.minecraft.init.Bootstrap.register(Bootstrap.java:560)
at net.minecraft.client.Minecraft.(Minecraft.java:380)
at net.minecraft.client.main.Main.main(Main.java:114)
Caused by: java.lang.NullPointerException
at java.io.Reader.(Reader.java:78)
at java.io.InputStreamReader.(InputStreamReader.java:113)
at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
at net.minecraft.util.StringTranslate.(StringTranslate.java:42)
at net.minecraft.util.StringTranslate.(StringTranslate.java:28)
... 10 more

**Comment by Alexander01998** [comment]
Duplicate: #629
