### ISSUE TITLE
Crash on newest Wurst Version

### ISSUE THREAD

**Issue by Whatisthisname** [Wurst-Imperium/Wurst-Client#673]
The screen turns completely black, its when i am at a guys plot on a server.

**Comment by Alexander01998** [comment]
When including error output, please wrap it into a [Markdown code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) so that it renders nicely.
Example:

<pre>```
java.lang.NullPointerException: null
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
```</pre>

**Comment by OMGchangeMYusername** [comment]
`````````
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why did you do that?

Time: 02-05-15 17:07
Description: Batching chunks

java.nio.BufferOverflowException
at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
at java.nio.IntBuffer.put(IntBuffer.java:859)
at net.minecraft.client.renderer.WorldRenderer.setVertexState(WorldRenderer.java:97)
at net.minecraft.client.renderer.chunk.RenderChunk.func_178570_a(RenderChunk.java:103)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:104)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:45)
at java.lang.Thread.run(Thread.java:745)
A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
at java.nio.IntBuffer.put(IntBuffer.java:859)
at net.minecraft.client.renderer.WorldRenderer.setVertexState(WorldRenderer.java:97)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['What_'/54557, l='MpServer', x=6558,00, y=70,00, z=-6373,45]]
Chunk stats: MultiplayerChunkCache: 170, 170
Level seed: 0
Level generator: ID 01 - flat, ver 0. Features enabled: false
Level generator options:
Level spawn location: 6560,00,67,00,-6400,00 - World: (6560,67,-6400), Chunk: (at 0,4,0 in 410,-400; contains blocks 6560,0,-6400 to 6575,255,-6385), Region: (12,-13; contains chunks 384,-416 to 415,-385, blocks 6144,0,-6656 to 6655,255,-6145)
Level time: 656784279 game time, 246000 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 8 total; [EntityMinecartEmpty['entity.MinecartRideable.name'/15891218, l='MpServer', x=6547,50, y=65,06, z=-6367,50], EntityMinecartEmpty['entity.MinecartRideable.name'/15891219, l='MpServer', x=6547,50, y=65,06, z=-6367,50], EntityMinecartEmpty['entity.MinecartRideable.name'/15891216, l='MpServer', x=6547,50, y=65,06, z=-6368,50], EntityMinecartEmpty['entity.MinecartRideable.name'/15891217, l='MpServer', x=6547,50, y=65,06, z=-6370,53], EntityMinecartEmpty['entity.MinecartRideable.name'/15891220, l='MpServer', x=6547,50, y=65,06, z=-6366,50], EntityMinecartEmpty['entity.MinecartRideable.name'/15891221, l='MpServer', x=6547,50, y=65,06, z=-6365,50], EntityPlayerSP['What_'/54557, l='MpServer', x=6558,00, y=70,00, z=-6373,45], EntityMinecartEmpty['entity.MinecartRideable.name'/15891215, l='MpServer', x=6547,50, y=65,06, z=-6369,50]]
Retry entities: 0 total; []
Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"f2d17cb":1052) <- Spigot
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:55)
at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
Minecraft Version: 1.8
Wurst Client Version: 1.14 (latest: 1.14)
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 109566960 bytes (104 MB) / 313856000 bytes (299 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: Wurst
LWJGL: 2.9.1
OpenGL: ERROR RuntimeException: No OpenGL context found in the current thread.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: [MLG Pack]
Current Language: English (US)
Profiler Position: N/A (disabled)
``````
is this good?

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername how you do that?

**Comment by GummiBoat** [comment]
You should read the page "Mastering Markdown".
```
Add 3 `<-of these in front and after the Code-Block.
```

**Comment by Nitrogen-Dioxide** [comment]
@GummiBoat thx

**Comment by SilverCreep** [comment]
I crash too :''(
Crash report:
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Don't be sad. I'll do better next time, I promise!

Time: 17/07/15 15:57
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.5.8
	Java Version: 1.6.0_26, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 133080184 bytes (126 MB) / 289726464 bytes (276 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce 9400M OpenGL Engine GL version 2.0 NVIDIA-1.5.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Français (France)
	Profiler Position: N/A (disabled)

**Comment by bob80333** [comment]
You have a different problem.  Update to Java 8.

**Comment by bob80333** [comment]
Issue #1224 has a link to the wiki's instructions to update.
