### ISSUE TITLE
Nuker Problem!

### ISSUE THREAD

**Issue by Loltage23** [Wurst-Imperium/Wurst-Client#698]
I was on a server an my game crashed!

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Oops.

Time: 03/05/15 21:03
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['AfcWimbledon'/359266, l='MpServer', x=1268.26, y=65.00, z=345.65], EntityOtherPlayerMP['BriggsPassGaming'/323411, l='MpServer', x=1256.33, y=67.13, z=341.77]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 1223.00,66.00,299.00 - World: (1223,66,299), Chunk: (at 7,4,11 in 76,18; contains blocks 1216,0,288 to 1231,255,303), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Level time: 383033687 game time, 426271822 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntityOtherPlayerMP['BriggsPassGaming'/323411, l='MpServer', x=1198.48, y=75.40, z=299.29], EntityPlayerSP['AfcWimbledon'/359266, l='MpServer', x=1268.26, y=65.00, z=345.65], EntityOtherPlayerMP['38Edward'/151970, l='MpServer', x=1194.57, y=87.59, z=341.03], EntityOtherPlayerMP['AfcWimbledon'/-69, l='MpServer', x=1249.86, y=91.11, z=267.64], EntityOtherPlayerMP['BriggsPassGaming'/323411, l='MpServer', x=1245.88, y=83.81, z=266.84], EntityOtherPlayerMP['BriggsPassGaming'/323411, l='MpServer', x=1256.33, y=67.13, z=341.77], EntityOtherPlayerMP['BriggsPassGaming'/323411, l='MpServer', x=1238.41, y=74.47, z=254.91], EntityOtherPlayerMP['BriggsPassGaming'/323411, l='MpServer', x=1256.33, y=67.13, z=341.77]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 118143488 bytes (112 MB) / 429613056 bytes (409 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 24, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.11, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Alexander01998** [comment]
Duplicate: #642
