### ISSUE TITLE
i updated java 8 but it still not work

### ISSUE THREAD

**Issue by arnont33** [Wurst-Imperium/Wurst-Client#703]
i updated java 6 to java 8 but it still not work
i checked my java version from java.com/en
it said i already have java 8
why i cant open wurst 1.14 i rly want to use it can any one  help me please
![screen shot 2558-05-05 at 18 45 41](https://cloud.githubusercontent.com/assets/11918011/7469452/0e2c2056-f357-11e4-918f-2d4d5430930e.png)
HELP ME PLEASE

**Comment by GummiBoat** [comment]
First, what executable are you running in your minecraft-launcher? (select the wurst profile, click Edit Profile and look at the executable.

If it's 1.8 in there, try deinstalling all of your java versions and install the newest version.

**Comment by arnont33** [comment]
sorry but i dont under stand
![screen shot 2558-05-05 at 20 27 17](https://cloud.githubusercontent.com/assets/11918011/7471001/35a9c2e2-f365-11e4-8b20-9ff5bf1c950b.png)
This is my profile editor
what should i do?
please help me

**Comment by GummiBoat** [comment]
Go to /System/library/Java/JavaVirtualMachines/ and look if 1.8.0jdk is in there.
Then go to your launcher again, and click the checkbox "Executable" and change the 1.6.0.jdk to 1.8.0jdk.

**Comment by arnont33** [comment]
ok ill do that thanks for help !

**Comment by arnont33** [comment]
i try to change Executable from 1.6 to 1.8 and click Play but it still not work
![screen shot 2558-05-05 at 21 33 05](https://cloud.githubusercontent.com/assets/11918011/7471788/6de0b41e-f36e-11e4-9f7f-4dad67821c9e.png)

**Comment by GummiBoat** [comment]
Could you leave information about the error it displays to you? The screenshot is not completed.

**Comment by arnont33** [comment]
its nothing hapen its blank screen when i click play button

**Comment by GummiBoat** [comment]
Then you included a wrong path for your executable. Make sure that your path really exists.

**Comment by scriptinator** [comment]
Try doing:
Which Java 
In terminal
If that returns /usr/bin or something like that
Ls -l THAT DIRECTORY
Then copy that path to the executable field in the launcher

**Comment by arnont33** [comment]
i cant find any file sorry
![screen shot 2558-05-06 at 9 33 42](https://cloud.githubusercontent.com/assets/11918011/7484990/1b2c3e4a-f3d3-11e4-9292-5cf423d9a184.png)
this is my finder

**Comment by arnont33** [comment]
i try this method from java but it still not work
![screen shot 2558-05-06 at 10 17 59](https://cloud.githubusercontent.com/assets/11918011/7485445/4886d804-f3d9-11e4-9eab-818ff1bcddf8.png)
when i do that
![screen shot 2558-05-06 at 10 19 16](https://cloud.githubusercontent.com/assets/11918011/7485458/683ee452-f3d9-11e4-8ffa-8dcc19f0e117.png)

**Comment by arnont33** [comment]
can any one help me ? plss

**Comment by eveythingistaken** [comment]
What is happening when it says it doesn't work?

**Comment by arnont33** [comment]
i updated java to java 8 but it still cant open wurst
can u help me?

**Comment by eveythingistaken** [comment]
I just asked what does it say when it doesn't work. Does it say something like "minecraft can't be opened on Java 8 with mac"?

**Comment by arnont33** [comment]
ok ill try that ,thanks for your help :D !

**Comment by arnont33** [comment]
i install java JDK 8u45 but it still not work D;
its same ,what should i do ?

**Comment by OMGchangeMYusername** [comment]
ok is this another crApple issue?

**Comment by arnont33** [comment]
sorry, but what is the crApple ?

**Comment by OMGchangeMYusername** [comment]
crApple is a word (which i assume Alexander made) used to describe Mac issues
(Apple..you know crApple..)

**Comment by Alexander01998** [comment]
> crApple is a word (which i assume Alexander made) used to describe Mac issues
> (Apple..you know crApple..)

The word crApple has been around for a long time (see [Google image search](https://www.google.com/search?q=crapple&tbm=isch)). Either me or @gruenwald32 found it sometime.

We did, however, make these things:
- [ollis-pc-wurst.cu.cc](http://www.ollis-pc-wurst.cu.cc/) - An impress.js presentation about @gruenwald32's favorite computer. Contains crApple jokes:
  - http://www.ollis-pc-wurst.cu.cc/#/titel (wait 5 seconds)
  - http://www.ollis-pc-wurst.cu.cc/#/ende (click on the crApple logo)
- [crapple.jimdo.com](http://crapple.jimdo.com/) - A website for crApple haters. Pretty much every page on it is a crApple joke.

**Comment by arnont33** [comment]
can u help me to use java 8 with mac ?
i installed it but it doesn't work D:

**Comment by OMGchangeMYusername** [comment]
didn't know such word existed :open_mouth: 
i thought you made it because of
> I talked to Grünwald32, the leader of the Wurst-Imperium anti-crApple movement.
:smiley:

**Comment by arnont33** [comment]
how

**Comment by Alexander01998** [comment]
> can u help me? i really want to use 1.14 D;

We will soon have a video about it on WiZARDHAX.

**Comment by arnont33** [comment]
thanksyou :D !

**Comment by arnont33** [comment]
thanksyou :D !

**Comment by arnont33** [comment]
thanksyou :D !

**Comment by arnont33** [comment]
ok thanks for help :D !

**Comment by arnont33** [comment]
![screen shot 2558-05-10 at 21 11 47](https://cloud.githubusercontent.com/assets/11918011/7554039/37f7db86-f759-11e4-9afc-a2367487daa2.png)
its nothing D;

**Comment by arnont33** [comment]
WOW Thanks VERY MUCH 
NOW i can Play Wurst 1.14  !!
XD

**Comment by wesnoah3** [comment]
Help!!! @paris-ci   @Alexander01998 
[12:46:33 INFO]: Minecraft Launcher 1.6.48 (through bootstrap 100) started on osx...
[12:46:33 INFO]: Current time is Dec 25, 2015 12:46:33 PM
[12:46:33 INFO]: System.getProperty('os.name') == 'Mac OS X'
[12:46:33 INFO]: System.getProperty('os.version') == '10.9.5'
[12:46:33 INFO]: System.getProperty('os.arch') == 'x86_64'
[12:46:33 INFO]: System.getProperty('java.version') == '1.8.0_60'
[12:46:33 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[12:46:33 INFO]: System.getProperty('sun.arch.data.model') == '64'
[12:46:33 INFO]: proxy == DIRECT
[12:46:34 INFO]: JFX is already initialized
[12:46:34 INFO]: Refreshing local version list...
[12:46:35 INFO]: Refreshing remote version list...
[12:46:36 INFO]: Refresh complete.
[12:46:37 INFO]: Loaded 6 profile(s); selected 'Wurst'
[12:46:37 INFO]: Refreshing auth...
[12:46:37 INFO]: Logging in with access token
[12:46:38 INFO]: Getting syncinfo for selected version
[12:46:38 INFO]: Queueing library & version downloads
[12:46:38 INFO]: Download job 'Version & Libraries' started (16 threads, 32 files)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.17/authlib-1.5.17.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries'... (try 0)
[12:46:38 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Download job 'Resources' skipped as there are no files to download
[12:46:39 INFO]: Job 'Resources' finished successfully (took 0:00:00.000)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/mojang/realms/1.5.5/realms-1.5.5.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/mojang/realms/1.5.5/realms-1.5.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Attempting to download /Users/wes/Library/Application Support/minecraft/versions/Wurst/Wurst.jar for job 'Version & Libraries'... (try 0)
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.17/authlib-1.5.17.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[12:46:39 INFO]: Finished downloading /Users/wes/Library/Application Support/minecraft/versions/Wurst/Wurst.jar for job 'Version & Libraries': Couldn't connect to server (responded with 403) but have local file, assuming it's good
[12:46:39 INFO]: Job 'Version & Libraries' finished successfully (took 0:00:00.827)
[12:46:39 INFO]: Launching game
[12:46:39 INFO]: Unpacking natives to /Users/wes/Library/Application Support/minecraft/versions/Wurst/Wurst-natives-3010524837248
[12:46:39 INFO]: Launching in /Users/wes/Library/Application Support/minecraft
[12:46:39 INFO]: Half command: /System/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/bin/java -Xdock:icon=/Users/wes/Library/Application Support/minecraft/assets/objects/99/991b421dfd401f115241601b2b373140a8d78572 -Xdock:name=Minecraft -Xmx1G -Djava.library.path=/Users/wes/Library/Application Support/minecraft/versions/Wurst/Wurst-natives-3010524837248 -cp /Users/wes/Library/Application Support/minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar:/Users/wes/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/Users/wes/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/wes/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:/Users/wes/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/wes/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/wes/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/wes/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.17/authlib-1.5.17.jar:/Users/wes/Library/Application Support/minecraft/libraries/com/mojang/realms/1.5.5/realms-1.5.5.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/Users/wes/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar:/Users/wes/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar:/Users/wes/Library/Application Support/minecraft/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar:/Users/wes/Library/Application Support/minecraft/versions/Wurst/Wurst.jar net.minecraft.client.main.Main
[12:46:39 ERROR]: Couldn't launch game
java.io.IOException: Cannot run program "/System/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/bin/java" (in directory "/Users/wes/Library/Application Support/minecraft"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_60]
	at com.mojang.launcher.game.process.direct.DirectGameProcessFactory.startGame(DirectGameProcessFactory.java:14) ~[launcher.jar:1.6.48]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:218) [launcher.jar:1.6.48]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:186) [launcher.jar:1.6.48]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:122) [launcher.jar:1.6.48]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:1.6.48]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher.jar:1.6.48]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_60]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~[?:1.8.0_60]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_60]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_60]
	... 11 more
[12:46:39 INFO]: Deleting /Users/wes/Library/Application Support/minecraft/versions/Wurst/Wurst-natives-3010524837248

**Comment by wesnoah3** [comment]
When I type java -version:
http://imgur.com/we6XcDf
I AM using the newest minecraft launcher.

Followed many uninstall instructions and install instructions and I believe they have worked.
Thanks!

**Comment by mcccs** [comment]
are you sure you downloaded [the jar version](https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar)

**Comment by wesnoah3** [comment]
Launcher 1.6.48?

**Comment by wesnoah3** [comment]
@mcccs

**Comment by mcccs** [comment]
No. Download and try it

**Comment by wesnoah3** [comment]
I don't know if I have the right thing. Can you link me to the download? @mcccs

**Comment by wesnoah3** [comment]
I did install it and it still says Java is outdated. Even tho I deleted the old java and install the newest version!?!

**Comment by mcccs** [comment]
go to java.com/verify
what does it say?

**Comment by mcccs** [comment]
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java
Paste this "In Minecraft>Edit Profile>Executable"

**Comment by wesnoah3** [comment]
Already installed jdk and checked that still only 1.6.0jdk in there :/

**Comment by wesnoah3** [comment]
@mcccs

**Comment by wesnoah3** [comment]
It worked! Thanks! My problem was I typed /System/ Before library and it brought me to a folder with only 1.6.0. Mine was /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java

**Comment by mcccs** [comment]
@wesnoah3 Don't forget, you should repeat these steps when you update java.

**Comment by wesnoah3** [comment]
Why and how? @mcccs

**Comment by mcccs** [comment]
Because when you update JDK the version changes.

**Comment by wesnoah3** [comment]
What steps though? Wurst already works? @mcccs

**Comment by mcccs** [comment]
Short version: Don't update JDK

**Comment by wesnoah3** [comment]
Why because I already did update it for wurst? @mcccs

**Comment by mcccs** [comment]
Never mind. JDK doesn't auto update. Just enjoy.

**Comment by wesnoah3** [comment]
Alright, thanks again!

**Comment by mcccs** [comment]
You are welcome!
