### ISSUE TITLE
.xray list resolves in error

### ISSUE THREAD

**Issue by GummiBoat** [Wurst-Imperium/Wurst-Client#751]
I don't know if the Auto-Reported Bug was send correctly (it didn't seem like it, but I'm not very firm with github yet.)

So I post it here too. I'll close it if it was wrong.

How to reproduce:

* Run Wurst regular.
* Join a server or enter a singleplayer world.
* Run the command .xray list

The message "X-Ray blocks list (page x/x):" shows, but nothing else (except for the Bug screen.)

> This is an auto-generated error report for the [Wurst Client](https://www.wurst-client.tk).

# Description
An error occurred in `.xray` while executing.
Exact input: `.xray list`

# Stacktrace
```
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:590)
	at tk.wurst_client.commands.XRayCmd.execute(XRayCmd.java:54)
	at tk.wurst_client.commands.XRayCmd.execute(XRayCmd.java:35)
	at tk.wurst_client.commands.CmdManager.onSentMessage(CmdManager.java:90)
	at net.minecraft.client.entity.EntityPlayerSP.sendChatMessage(EntityPlayerSP.java:281)
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:487)
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:477)
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:132)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:617)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:568)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1970)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1300)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)

```

# System details
- OS: Windows 7 (x86)
- Java version: 1.8.0_45 (Oracle Corporation)
- Wurst version: 1.14 (latest: 1.14)
- Timestamp: 2015.05.12-01:04:32

**Comment by OMGchangeMYusername** [comment]
did that command exist O.o?

**Comment by GummiBoat** [comment]
Afaik, yes.

**Comment by OMGchangeMYusername** [comment]
Confirmed :P
The pages 2,3,5 are working fine for me tho `.xray list 2`etc..

**Comment by Alexander01998** [comment]
> I don't know if the Auto-Reported Bug was send correctly

It was, I found it on the [error reports list](https://www.wurst-client.tk/error-reports/).

> (it didn't seem like it, but I'm not very firm with github yet.)

You should have seen something like `Server response: Thanks for reporting! <3` in the chat.

**Comment by GummiBoat** [comment]
Ah, okay, thanks :+1:
