### ISSUE TITLE
Wurst randomly crashes when opening chat

### ISSUE THREAD

**Issue by redkilllerz45p** [Wurst-Imperium/Wurst-Client#850]
The only thing I can understand in this crash report is that it happened when I tried to open the chat and some other GUI thingy...
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// But it works on my machine.

Time: 01/06/15 13:48
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 8 total; removed
	Chunk stats: MultiplayerChunkCache: 440, 440
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 53.00,234.00,53.00 - World: (53,234,53), Chunk: (at 5,14,5 in 3,3; contains blocks 48,0,48 to 63,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3018276 game time, 3744000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 18 total; removed
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"772c8d7":1019) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// But it works on my machine.

Time: 01/06/15 13:48
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: removed
	Chunk stats: MultiplayerChunkCache: 440, 440
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 53.00,234.00,53.00 - World: (53,234,53), Chunk: (at 5,14,5 in 3,3; contains blocks 48,0,48 to 63,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3018276 game time, 3744000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 18 total; removed
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"772c8d7":1019) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14.1)
	Operating System: Linux (amd64) version 3.19.0-20-generic
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 318351576 bytes (303 MB) / 539025408 bytes (514 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:MaxPermSize=128m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 49, allocated: 13, tallocated: 95
	Launched Version: Wurst 1.8
	LWJGL: 2.9.1
	OpenGL: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0 NVIDIA 340.76, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14.1)
	Operating System: Linux (amd64) version 3.19.0-20-generic
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 318351576 bytes (303 MB) / 539025408 bytes (514 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:MaxPermSize=128m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 49, allocated: 13, tallocated: 95
	Launched Version: Wurst 1.8
	LWJGL: 2.9.1
	OpenGL: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0 NVIDIA 340.76, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)

**Comment by Alexander01998** [comment]
Duplicate: #642
