### ISSUE TITLE
AltManager Crash

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#855]
STEPS TO CRASH

Click use on alt that doesn't work
Click use on alt that does work
Crash

```
--------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Who set us up the TNT?

Time: 6/3/15 2:11 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tk.wurst_client.alts.gui.GuiAlts.actionPerformed(GuiAlts.java:101)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.alts.gui.GuiAlts.mouseClicked(GuiAlts.java:249)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1971)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1300)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tk.wurst_client.alts.gui.GuiAlts.actionPerformed(GuiAlts.java:101)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.alts.gui.GuiAlts.mouseClicked(GuiAlts.java:249)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: tk.wurst_client.alts.gui.GuiAlts
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1971)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1300)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14.1 (latest: 1.14.1)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 244968216 bytes (233 MB) / 381530112 bytes (363 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3412, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
> STEPS TO CRASH
> 
> Click use on alt that doesn't work
> Click use on alt that does work
> Crash

Working just fine.

**Comment by Alexander01998** [comment]
Lists in Minecraft sometimes do this for no clear reason.
