### ISSUE TITLE
Keybind Menu Crash (Remove Button)

### ISSUE THREAD

**Issue by WurstContributer12345** [Wurst-Imperium/Wurst-Client#885]
Crash report:
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Ouch. That hurt :(

Time: 6/6/15 11:38 AM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 12
	at tk.wurst_client.options.gui.GuiKeybindManager.actionPerformed(GuiKeybindManager.java:78)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiKeybindManager.mouseClicked(GuiKeybindManager.java:110)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1971)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1300)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.options.gui.GuiKeybindManager.actionPerformed(GuiKeybindManager.java:78)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
	at tk.wurst_client.options.gui.GuiKeybindManager.mouseClicked(GuiKeybindManager.java:110)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: tk.wurst_client.options.gui.GuiKeybindManager

-- Affected level --
Details:
	Level name: MpServer
	All players: [removed]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 27.00,4.00,555.00 - World: (27,4,555), Chunk: (at 11,0,11 in 1,34; contains blocks 16,0,544 to 31,255,559), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 38716 game time, 12394 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: [removed]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2950)
	at net.minecraft.client.Minecraft.run(Minecraft.java:433)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14.1 (latest: 1.14.1)
	Operating System: Linux (amd64) version 3.19.0-15-generic
	Java Version: 1.8.0_45-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 152157048 bytes (145 MB) / 314753024 bytes (300 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Mesa DRI Intel(R) Ironlake Mobile  GL version 2.1 Mesa 10.6.0-devel, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
When including error output, please wrap it into a [Markdown code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) so that it renders nicely.
Example:

<pre>```
java.lang.NullPointerException: null
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
```</pre>

**Comment by WurstContributer12345** [comment]
Updated.

**Comment by Alexander01998** [comment]
Could not be reproduced, but should be fixed.
