### ISSUE TITLE
Freecam Crash (Slabs)

### ISSUE THREAD

**Issue by WurstContributer12345** [Wurst-Imperium/Wurst-Client#886]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I blame Dinnerbone.

Time: 6/6/15 9:09 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockState{block=minecraft:double_stone_slab, properties=[seamless, variant]}
	at net.minecraft.block.state.BlockState$StateImplemenation.getValue(BlockState.java:150)
	at net.minecraft.world.World.doesBlockHaveSolidTopSurface(World.java:2422)
	at net.minecraft.block.BlockLiquid.randomDisplayTick(BlockLiquid.java:282)
	at net.minecraft.client.multiplayer.WorldClient.doVoidFogParticles(WorldClient.java:318)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2441)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1300)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplemenation.getValue(BlockState.java:150)
	at net.minecraft.world.World.doesBlockHaveSolidTopSurface(World.java:2422)
	at net.minecraft.block.BlockLiquid.randomDisplayTick(BlockLiquid.java:282)
	at net.minecraft.client.multiplayer.WorldClient.doVoidFogParticles(WorldClient.java:318)

-- Affected level --
Details:
	Level name: MpServer
	All players: [removed]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -15749.00,206.00,19597.00 - World: (-15749,206,19597), Chunk: (at 11,12,13 in -985,1224; contains blocks -15760,0,19584 to -15745,255,19599), Region: (-31,38; contains chunks -992,1216 to -961,1247, blocks -15872,0,19456 to -15361,255,19967)
	Level time: 996729438 game time, 997536875 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 53 total; [removed]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"e6da9cb":1040) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2950)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14.1 (latest: 1.14.1)
	Operating System: Linux (amd64) version 3.19.0-15-generic
	Java Version: 1.8.0_45-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 103010720 bytes (98 MB) / 285360128 bytes (272 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: Mesa DRI Intel(R) Ironlake Mobile  GL version 2.1 Mesa 10.6.0-devel, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Alexander01998** [comment]
Duplicate: #124
