### ISSUE TITLE
This Crash

### ISSUE THREAD

**Issue by wuofwhat** [Wurst-Imperium/Wurst-Client#95]
```
Time: 27.2.2015 15:08
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:357)
	at tk.wurst_client.files.FileManager.init(FileManager.java:89)
	at tk.wurst_client.Client.startClient(Client.java:54)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:616)
	at net.minecraft.client.Minecraft.run(Minecraft.java:429)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:357)
	at tk.wurst_client.files.FileManager.init(FileManager.java:89)
	at tk.wurst_client.Client.startClient(Client.java:54)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:616)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:429)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.6 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 393471376 bytes (375 MB) / 666763264 bytes (635 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.2.46, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Sphax PureBDcraft 128x MC18]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
```

Any ideas?

**Comment by Alexander01998** [comment]
Looks like the file manager had a problem with your alt list.
If it's an alt list from Wurst v1.5.X, remember to convert it into the new format.

**Comment by Alexander01998** [comment]
Also, update to Java 8.

**Comment by Notchshero** [comment]
Updating to java 8 isnt easy on macs. (I tried, i couldnt do it!) But if you want a small chance: http://www.cgwerks.com/make-minecraft-work-mac-osx-yosemite-latest-java-8/
