### ISSUE TITLE
Crash Report:

### ISSUE THREAD

**Issue by Delivator** [Wurst-Imperium/Wurst-Client#96]
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Sorry :(

Time: 27.02.15 15:55
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to java.lang.String
	at net.minecraft.entity.DataWatcher.getWatchableObjectString(DataWatcher.java:116)
	at net.minecraft.entity.Entity.hasCustomName(Entity.java:2622)
	at net.minecraft.entity.Entity.getName(Entity.java:2362)
	at net.minecraft.client.renderer.entity.Render.renderLivingLabel(Render.java:377)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_147914_a(RenderItemFrame.java:228)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.doRender(RenderItemFrame.java:83)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.doRender(RenderItemFrame.java:255)
	at net.minecraft.client.renderer.entity.RenderManager.doRenderEntity(RenderManager.java:381)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:338)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntitySimple(RenderManager.java:305)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:658)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1419)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1333)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1158)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1361)
	at net.minecraft.client.Minecraft.run(Minecraft.java:449)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.getWatchableObjectString(DataWatcher.java:116)
	at net.minecraft.entity.Entity.hasCustomName(Entity.java:2622)
	at net.minecraft.entity.Entity.getName(Entity.java:2362)
	at net.minecraft.client.renderer.entity.Render.renderLivingLabel(Render.java:377)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.func_147914_a(RenderItemFrame.java:228)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.doRender(RenderItemFrame.java:83)
	at net.minecraft.client.renderer.tileentity.RenderItemFrame.doRender(RenderItemFrame.java:255)

-- Entity being rendered --
Details:
	Entity Type: ItemFrame (net.minecraft.entity.item.EntityItemFrame)
	Entity ID: 25042
	Entity Name: ~~ERROR~~ ClassCastException: net.minecraft.item.ItemStack cannot be cast to java.lang.String
	Entity's Exact location: -726,03, 6,50, 1199,50
	Entity's Block location: -727,00,6,00,1199,00 - World: (-727,6,1199), Chunk: (at 9,0,15 in -46,74; contains blocks -736,0,1184 to -721,255,1199), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.tileentity.RenderItemFrame@392c2cd0
	Location: 1,12,2,50,-0,87 - World: (1,2,-1), Chunk: (at 1,0,15 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 90.0
	Delta: 0.2837113
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.doRenderEntity(RenderManager.java:381)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:338)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntitySimple(RenderManager.java:305)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:658)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1419)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1333)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Delivator'/25916, l='MpServer', x=-727,14, y=4,00, z=1200,21], EntityOtherPlayerMP['easyplaying'/24989, l='MpServer', x=-725,84, y=4,00, z=1204,60]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -758,00,14,00,1209,00 - World: (-758,14,1209), Chunk: (at 10,0,9 in -48,75; contains blocks -768,0,1200 to -753,255,1215), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Level time: 227338471 game time, 1152110444 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: ~~ERROR~~ ClassCastException: net.minecraft.item.ItemStack cannot be cast to java.lang.String
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2992)
	at net.minecraft.client.Minecraft.run(Minecraft.java:471)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.6 (latest: 1.6)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 202222248 bytes (192 MB) / 452272128 bytes (431 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R9 200 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
When did this happen?

**Comment by Delivator** [comment]
I walk arround in a server and it crashed randomly? And one question, bist du deutsch? :D

**Comment by Alexander01998** [comment]
> I walk arround in a server and it crashed randomly?

Alright, I know what this is. This is a weird bug that happens very very rarely. The last time I saw this was in Minecraft 1.7 and I thought that I fixed it there. Seems like I didn't.

> And one question, bist du deutsch? :D

Yes, but all Issues have to be in English. It's part of the international documentation and shit.
