### ISSUE TITLE
Crash on Wurst v1.6

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#97]
I just installed the new version of Wurst which adds auto stealer, safety for alts, etc. Now whenever I open Minecraft it crashes. Not sure why but here's all the code it says when it crashes. 

Thanks.

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Daisy, daisy...

Time: 2/27/15 10:08 AM
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:357)
	at tk.wurst_client.files.FileManager.init(FileManager.java:89)
	at tk.wurst_client.Client.startClient(Client.java:54)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:616)
	at net.minecraft.client.Minecraft.run(Minecraft.java:429)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:357)
	at tk.wurst_client.files.FileManager.init(FileManager.java:89)
	at tk.wurst_client.Client.startClient(Client.java:54)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:616)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:429)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.6 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 114043672 bytes (108 MB) / 267902976 bytes (255 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 640M OpenGL Engine GL version 2.1 NVIDIA-10.2.1 310.41.15f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Sphax PureBDcraft  32x MC18]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
Update to Java 8.

**Comment by Notchshero** [comment]
Updating to java 8 isnt easy on macs. (I tried, i couldnt do it!) But if you want a small chance: http://www.cgwerks.com/make-minecraft-work-mac-osx-yosemite-latest-java-8/

**Comment by Alexander01998** [comment]
> Updating to java 8 isnt easy on macs. (I tried, i couldnt do it!)

One more reason why Windows is better. :computer:

**Comment by eveythingistaken** [comment]
Notchshero I tried too xD it is very difficult. Right now I'm on Java 6. Would Java 7 make it work? Or just Java 8?

**Comment by Alexander01998** [comment]
> Notchshero I tried too xD it is very difficult. Right now I'm on Java 6. Would Java 7 make it work? Or just Java 8?

The new AltManager encryption requires the new features and security fixes in Java 8.

**Comment by GlitchHead** [comment]
Here is a simple link to install java 8 on a mac http://bit.ly/1DGZYQK

**Comment by eveythingistaken** [comment]
Glitch head did you make that little animation 😂

**Comment by Notchshero** [comment]
Oh it only installs java 8. But you MUST delete java and reinstall. (It says java 6 is installed [Not the real java 6, it is crApple made Java called java 2014-01 or etc.] even you installed java 8)
